language: ruby

sudo: false

cache:
  bundler: true

rvm:
  - 2.4
  - 2.5
  - 2.6
  - ruby-head

jobs:
  allow_failures:
  - rvm: ruby-head

bundler_args: --jobs 3 --retry 3

script: 'bundle exec rspec'
