# encoding: UTF-8
# Generated by wsdl2ruby (SOAP4R-NG/2.0.6)
require 'xsd/qname'

module UKMail; module SoapService; module Consignment


# {http://www.UKMail.com/Services/Contracts/DataContracts}WebRequest
#   authenticationToken - SOAP::SOAPString
#   username - SOAP::SOAPString
class WebRequest
  attr_accessor :authenticationToken
  attr_accessor :username

  def initialize(authenticationToken = nil, username = nil)
    @authenticationToken = authenticationToken
    @username = username
  end
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}AddDomesticConsignmentWebRequestV2
#   authenticationToken - SOAP::SOAPString
#   username - SOAP::SOAPString
#   accountNumber - SOAP::SOAPString
#   alternativeRef - SOAP::SOAPString
#   bookIn - SOAP::SOAPBoolean
#   businessName - SOAP::SOAPString
#   collectionDate - SOAP::SOAPDateTime
#   collectionJobNumber - SOAP::SOAPString
#   confirmationOfDelivery - SOAP::SOAPBoolean
#   contactName - SOAP::SOAPString
#   currencyCode - SOAP::SOAPString
#   customersRef - SOAP::SOAPString
#   descriptionOfGoods - SOAP::SOAPString
#   email - SOAP::SOAPString
#   exchangeOnDelivery - SOAP::SOAPBoolean
#   extendedCover - SOAP::SOAPInt
#   firstMileDropOff - SOAP::SOAPBoolean
#   height - SOAP::SOAPInt
#   inboxReturn - SOAP::SOAPBoolean
#   items - SOAP::SOAPInt
#   labelFormat - SOAP::SOAPString
#   length - SOAP::SOAPInt
#   longLength - SOAP::SOAPBoolean
#   preDeliveryNotification - UKMail::SoapService::Consignment::PreDeliveryNotificationType
#   recipientAddressList - UKMail::SoapService::Consignment::ArrayOfAddress
#   returnAccountNumber - SOAP::SOAPString
#   returnCustomerReference - SOAP::SOAPString
#   secureLocation1 - SOAP::SOAPString
#   secureLocation2 - SOAP::SOAPString
#   serviceKey - SOAP::SOAPInt
#   servicePointId - SOAP::SOAPString
#   signatureOptional - SOAP::SOAPBoolean
#   specialInstructions1 - SOAP::SOAPString
#   specialInstructions2 - SOAP::SOAPString
#   telephone - SOAP::SOAPString
#   value - SOAP::SOAPDecimal
#   weight - SOAP::SOAPDecimal
#   width - SOAP::SOAPInt
#   clearance - UKMail::SoapService::Consignment::Clearance
class AddDomesticConsignmentWebRequestV2 < WebRequest
  attr_accessor :authenticationToken
  attr_accessor :username
  attr_accessor :accountNumber
  attr_accessor :alternativeRef
  attr_accessor :bookIn
  attr_accessor :businessName
  attr_accessor :collectionDate
  attr_accessor :collectionJobNumber
  attr_accessor :confirmationOfDelivery
  attr_accessor :contactName
  attr_accessor :currencyCode
  attr_accessor :customersRef
  attr_accessor :descriptionOfGoods
  attr_accessor :email
  attr_accessor :exchangeOnDelivery
  attr_accessor :extendedCover
  attr_accessor :firstMileDropOff
  attr_accessor :height
  attr_accessor :inboxReturn
  attr_accessor :items
  attr_accessor :labelFormat
  attr_accessor :length
  attr_accessor :longLength
  attr_accessor :preDeliveryNotification
  attr_accessor :recipientAddressList
  attr_accessor :returnAccountNumber
  attr_accessor :returnCustomerReference
  attr_accessor :secureLocation1
  attr_accessor :secureLocation2
  attr_accessor :serviceKey
  attr_accessor :servicePointId
  attr_accessor :signatureOptional
  attr_accessor :specialInstructions1
  attr_accessor :specialInstructions2
  attr_accessor :telephone
  attr_accessor :value
  attr_accessor :weight
  attr_accessor :width
  attr_accessor :clearance

  def initialize(authenticationToken = nil, username = nil, accountNumber = nil, alternativeRef = nil, bookIn = nil, businessName = nil, collectionDate = nil, collectionJobNumber = nil, confirmationOfDelivery = nil, contactName = nil, currencyCode = nil, customersRef = nil, descriptionOfGoods = nil, email = nil, exchangeOnDelivery = nil, extendedCover = nil, firstMileDropOff = nil, height = nil, inboxReturn = nil, items = nil, labelFormat = nil, length = nil, longLength = nil, preDeliveryNotification = nil, recipientAddressList = nil, returnAccountNumber = nil, returnCustomerReference = nil, secureLocation1 = nil, secureLocation2 = nil, serviceKey = nil, servicePointId = nil, signatureOptional = nil, specialInstructions1 = nil, specialInstructions2 = nil, telephone = nil, value = nil, weight = nil, width = nil, clearance = nil)
    @authenticationToken = authenticationToken
    @username = username
    @accountNumber = accountNumber
    @alternativeRef = alternativeRef
    @bookIn = bookIn
    @businessName = businessName
    @collectionDate = collectionDate
    @collectionJobNumber = collectionJobNumber
    @confirmationOfDelivery = confirmationOfDelivery
    @contactName = contactName
    @currencyCode = currencyCode
    @customersRef = customersRef
    @descriptionOfGoods = descriptionOfGoods
    @email = email
    @exchangeOnDelivery = exchangeOnDelivery
    @extendedCover = extendedCover
    @firstMileDropOff = firstMileDropOff
    @height = height
    @inboxReturn = inboxReturn
    @items = items
    @labelFormat = labelFormat
    @length = length
    @longLength = longLength
    @preDeliveryNotification = preDeliveryNotification
    @recipientAddressList = recipientAddressList
    @returnAccountNumber = returnAccountNumber
    @returnCustomerReference = returnCustomerReference
    @secureLocation1 = secureLocation1
    @secureLocation2 = secureLocation2
    @serviceKey = serviceKey
    @servicePointId = servicePointId
    @signatureOptional = signatureOptional
    @specialInstructions1 = specialInstructions1
    @specialInstructions2 = specialInstructions2
    @telephone = telephone
    @value = value
    @weight = weight
    @width = width
    @clearance = clearance
  end
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}AddDomesticConsignmentWebRequestV3
#   authenticationToken - SOAP::SOAPString
#   username - SOAP::SOAPString
#   accountNumber - SOAP::SOAPString
#   alternativeRef - SOAP::SOAPString
#   bookIn - SOAP::SOAPBoolean
#   businessName - SOAP::SOAPString
#   collectionDate - SOAP::SOAPDateTime
#   collectionJobNumber - SOAP::SOAPString
#   confirmationOfDelivery - SOAP::SOAPBoolean
#   contactName - SOAP::SOAPString
#   currencyCode - SOAP::SOAPString
#   customersRef - SOAP::SOAPString
#   descriptionOfGoods - SOAP::SOAPString
#   email - SOAP::SOAPString
#   exchangeOnDelivery - SOAP::SOAPBoolean
#   extendedCover - SOAP::SOAPInt
#   firstMileDropOff - SOAP::SOAPBoolean
#   height - SOAP::SOAPInt
#   inboxReturn - SOAP::SOAPBoolean
#   items - SOAP::SOAPInt
#   labelFormat - SOAP::SOAPString
#   length - SOAP::SOAPInt
#   longLength - SOAP::SOAPBoolean
#   preDeliveryNotification - UKMail::SoapService::Consignment::PreDeliveryNotificationType
#   recipientAddressList - UKMail::SoapService::Consignment::ArrayOfAddress
#   returnAccountNumber - SOAP::SOAPString
#   returnCustomerReference - SOAP::SOAPString
#   secureLocation1 - SOAP::SOAPString
#   secureLocation2 - SOAP::SOAPString
#   serviceKey - SOAP::SOAPInt
#   servicePointId - SOAP::SOAPString
#   signatureOptional - SOAP::SOAPBoolean
#   specialInstructions1 - SOAP::SOAPString
#   specialInstructions2 - SOAP::SOAPString
#   telephone - SOAP::SOAPString
#   value - SOAP::SOAPDecimal
#   weight - SOAP::SOAPDecimal
#   width - SOAP::SOAPInt
#   clearance - UKMail::SoapService::Consignment::Clearance
#   basicCustomsDeclaration - UKMail::SoapService::Consignment::BasicCustomsDeclaration
#   fullCustomsDeclaration - UKMail::SoapService::Consignment::CustomsDeclaration
class AddDomesticConsignmentWebRequestV3 < AddDomesticConsignmentWebRequestV2
  attr_accessor :authenticationToken
  attr_accessor :username
  attr_accessor :accountNumber
  attr_accessor :alternativeRef
  attr_accessor :bookIn
  attr_accessor :businessName
  attr_accessor :collectionDate
  attr_accessor :collectionJobNumber
  attr_accessor :confirmationOfDelivery
  attr_accessor :contactName
  attr_accessor :currencyCode
  attr_accessor :customersRef
  attr_accessor :descriptionOfGoods
  attr_accessor :email
  attr_accessor :exchangeOnDelivery
  attr_accessor :extendedCover
  attr_accessor :firstMileDropOff
  attr_accessor :height
  attr_accessor :inboxReturn
  attr_accessor :items
  attr_accessor :labelFormat
  attr_accessor :length
  attr_accessor :longLength
  attr_accessor :preDeliveryNotification
  attr_accessor :recipientAddressList
  attr_accessor :returnAccountNumber
  attr_accessor :returnCustomerReference
  attr_accessor :secureLocation1
  attr_accessor :secureLocation2
  attr_accessor :serviceKey
  attr_accessor :servicePointId
  attr_accessor :signatureOptional
  attr_accessor :specialInstructions1
  attr_accessor :specialInstructions2
  attr_accessor :telephone
  attr_accessor :value
  attr_accessor :weight
  attr_accessor :width
  attr_accessor :clearance
  attr_accessor :basicCustomsDeclaration
  attr_accessor :fullCustomsDeclaration

  def initialize(authenticationToken = nil, username = nil, accountNumber = nil, alternativeRef = nil, bookIn = nil, businessName = nil, collectionDate = nil, collectionJobNumber = nil, confirmationOfDelivery = nil, contactName = nil, currencyCode = nil, customersRef = nil, descriptionOfGoods = nil, email = nil, exchangeOnDelivery = nil, extendedCover = nil, firstMileDropOff = nil, height = nil, inboxReturn = nil, items = nil, labelFormat = nil, length = nil, longLength = nil, preDeliveryNotification = nil, recipientAddressList = nil, returnAccountNumber = nil, returnCustomerReference = nil, secureLocation1 = nil, secureLocation2 = nil, serviceKey = nil, servicePointId = nil, signatureOptional = nil, specialInstructions1 = nil, specialInstructions2 = nil, telephone = nil, value = nil, weight = nil, width = nil, clearance = nil, basicCustomsDeclaration = nil, fullCustomsDeclaration = nil)
    @authenticationToken = authenticationToken
    @username = username
    @accountNumber = accountNumber
    @alternativeRef = alternativeRef
    @bookIn = bookIn
    @businessName = businessName
    @collectionDate = collectionDate
    @collectionJobNumber = collectionJobNumber
    @confirmationOfDelivery = confirmationOfDelivery
    @contactName = contactName
    @currencyCode = currencyCode
    @customersRef = customersRef
    @descriptionOfGoods = descriptionOfGoods
    @email = email
    @exchangeOnDelivery = exchangeOnDelivery
    @extendedCover = extendedCover
    @firstMileDropOff = firstMileDropOff
    @height = height
    @inboxReturn = inboxReturn
    @items = items
    @labelFormat = labelFormat
    @length = length
    @longLength = longLength
    @preDeliveryNotification = preDeliveryNotification
    @recipientAddressList = recipientAddressList
    @returnAccountNumber = returnAccountNumber
    @returnCustomerReference = returnCustomerReference
    @secureLocation1 = secureLocation1
    @secureLocation2 = secureLocation2
    @serviceKey = serviceKey
    @servicePointId = servicePointId
    @signatureOptional = signatureOptional
    @specialInstructions1 = specialInstructions1
    @specialInstructions2 = specialInstructions2
    @telephone = telephone
    @value = value
    @weight = weight
    @width = width
    @clearance = clearance
    @basicCustomsDeclaration = basicCustomsDeclaration
    @fullCustomsDeclaration = fullCustomsDeclaration
  end
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}AddConsignmentWebRequest
#   authenticationToken - SOAP::SOAPString
#   username - SOAP::SOAPString
#   accountNumber - SOAP::SOAPString
#   address - UKMail::SoapService::Consignment::AddressWebModel
#   alternativeRef - SOAP::SOAPString
#   businessName - SOAP::SOAPString
#   collectionJobNumber - SOAP::SOAPString
#   confirmationOfDelivery - SOAP::SOAPBoolean
#   contactName - SOAP::SOAPString
#   customersRef - SOAP::SOAPString
#   email - SOAP::SOAPString
#   firstMileDropOff - SOAP::SOAPBoolean
#   items - SOAP::SOAPInt
#   serviceKey - SOAP::SOAPInt
#   specialInstructions1 - SOAP::SOAPString
#   specialInstructions2 - SOAP::SOAPString
#   telephone - SOAP::SOAPString
#   weight - SOAP::SOAPDecimal
class AddConsignmentWebRequest < WebRequest
  attr_accessor :authenticationToken
  attr_accessor :username
  attr_accessor :accountNumber
  attr_accessor :address
  attr_accessor :alternativeRef
  attr_accessor :businessName
  attr_accessor :collectionJobNumber
  attr_accessor :confirmationOfDelivery
  attr_accessor :contactName
  attr_accessor :customersRef
  attr_accessor :email
  attr_accessor :firstMileDropOff
  attr_accessor :items
  attr_accessor :serviceKey
  attr_accessor :specialInstructions1
  attr_accessor :specialInstructions2
  attr_accessor :telephone
  attr_accessor :weight

  def initialize(authenticationToken = nil, username = nil, accountNumber = nil, address = nil, alternativeRef = nil, businessName = nil, collectionJobNumber = nil, confirmationOfDelivery = nil, contactName = nil, customersRef = nil, email = nil, firstMileDropOff = nil, items = nil, serviceKey = nil, specialInstructions1 = nil, specialInstructions2 = nil, telephone = nil, weight = nil)
    @authenticationToken = authenticationToken
    @username = username
    @accountNumber = accountNumber
    @address = address
    @alternativeRef = alternativeRef
    @businessName = businessName
    @collectionJobNumber = collectionJobNumber
    @confirmationOfDelivery = confirmationOfDelivery
    @contactName = contactName
    @customersRef = customersRef
    @email = email
    @firstMileDropOff = firstMileDropOff
    @items = items
    @serviceKey = serviceKey
    @specialInstructions1 = specialInstructions1
    @specialInstructions2 = specialInstructions2
    @telephone = telephone
    @weight = weight
  end
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}AddDomesticConsignmentWebRequest
#   authenticationToken - SOAP::SOAPString
#   username - SOAP::SOAPString
#   accountNumber - SOAP::SOAPString
#   address - UKMail::SoapService::Consignment::AddressWebModel
#   alternativeRef - SOAP::SOAPString
#   businessName - SOAP::SOAPString
#   collectionJobNumber - SOAP::SOAPString
#   confirmationOfDelivery - SOAP::SOAPBoolean
#   contactName - SOAP::SOAPString
#   customersRef - SOAP::SOAPString
#   email - SOAP::SOAPString
#   firstMileDropOff - SOAP::SOAPBoolean
#   items - SOAP::SOAPInt
#   serviceKey - SOAP::SOAPInt
#   specialInstructions1 - SOAP::SOAPString
#   specialInstructions2 - SOAP::SOAPString
#   telephone - SOAP::SOAPString
#   weight - SOAP::SOAPDecimal
#   bookIn - SOAP::SOAPBoolean
#   cODAmount - SOAP::SOAPDecimal
#   confirmationEmail - SOAP::SOAPString
#   confirmationTelephone - SOAP::SOAPString
#   exchangeOnDelivery - SOAP::SOAPBoolean
#   extendedCover - SOAP::SOAPInt
#   longLength - SOAP::SOAPBoolean
#   preDeliveryNotification - UKMail::SoapService::Consignment::PreDeliveryNotificationType
#   secureLocation1 - SOAP::SOAPString
#   secureLocation2 - SOAP::SOAPString
#   signatureOptional - SOAP::SOAPBoolean
#   clearance - UKMail::SoapService::Consignment::Clearance
class AddDomesticConsignmentWebRequest < AddConsignmentWebRequest
  attr_accessor :authenticationToken
  attr_accessor :username
  attr_accessor :accountNumber
  attr_accessor :address
  attr_accessor :alternativeRef
  attr_accessor :businessName
  attr_accessor :collectionJobNumber
  attr_accessor :confirmationOfDelivery
  attr_accessor :contactName
  attr_accessor :customersRef
  attr_accessor :email
  attr_accessor :firstMileDropOff
  attr_accessor :items
  attr_accessor :serviceKey
  attr_accessor :specialInstructions1
  attr_accessor :specialInstructions2
  attr_accessor :telephone
  attr_accessor :weight
  attr_accessor :bookIn
  attr_accessor :cODAmount
  attr_accessor :confirmationEmail
  attr_accessor :confirmationTelephone
  attr_accessor :exchangeOnDelivery
  attr_accessor :extendedCover
  attr_accessor :longLength
  attr_accessor :preDeliveryNotification
  attr_accessor :secureLocation1
  attr_accessor :secureLocation2
  attr_accessor :signatureOptional
  attr_accessor :clearance

  def initialize(authenticationToken = nil, username = nil, accountNumber = nil, address = nil, alternativeRef = nil, businessName = nil, collectionJobNumber = nil, confirmationOfDelivery = nil, contactName = nil, customersRef = nil, email = nil, firstMileDropOff = nil, items = nil, serviceKey = nil, specialInstructions1 = nil, specialInstructions2 = nil, telephone = nil, weight = nil, bookIn = nil, cODAmount = nil, confirmationEmail = nil, confirmationTelephone = nil, exchangeOnDelivery = nil, extendedCover = nil, longLength = nil, preDeliveryNotification = nil, secureLocation1 = nil, secureLocation2 = nil, signatureOptional = nil, clearance = nil)
    @authenticationToken = authenticationToken
    @username = username
    @accountNumber = accountNumber
    @address = address
    @alternativeRef = alternativeRef
    @businessName = businessName
    @collectionJobNumber = collectionJobNumber
    @confirmationOfDelivery = confirmationOfDelivery
    @contactName = contactName
    @customersRef = customersRef
    @email = email
    @firstMileDropOff = firstMileDropOff
    @items = items
    @serviceKey = serviceKey
    @specialInstructions1 = specialInstructions1
    @specialInstructions2 = specialInstructions2
    @telephone = telephone
    @weight = weight
    @bookIn = bookIn
    @cODAmount = cODAmount
    @confirmationEmail = confirmationEmail
    @confirmationTelephone = confirmationTelephone
    @exchangeOnDelivery = exchangeOnDelivery
    @extendedCover = extendedCover
    @longLength = longLength
    @preDeliveryNotification = preDeliveryNotification
    @secureLocation1 = secureLocation1
    @secureLocation2 = secureLocation2
    @signatureOptional = signatureOptional
    @clearance = clearance
  end
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}AddInternationalConsignmentWebRequest
#   authenticationToken - SOAP::SOAPString
#   username - SOAP::SOAPString
#   accountNumber - SOAP::SOAPString
#   address - UKMail::SoapService::Consignment::AddressWebModel
#   alternativeRef - SOAP::SOAPString
#   businessName - SOAP::SOAPString
#   collectionJobNumber - SOAP::SOAPString
#   confirmationOfDelivery - SOAP::SOAPBoolean
#   contactName - SOAP::SOAPString
#   customersRef - SOAP::SOAPString
#   email - SOAP::SOAPString
#   firstMileDropOff - SOAP::SOAPBoolean
#   items - SOAP::SOAPInt
#   serviceKey - SOAP::SOAPInt
#   specialInstructions1 - SOAP::SOAPString
#   specialInstructions2 - SOAP::SOAPString
#   telephone - SOAP::SOAPString
#   weight - SOAP::SOAPDecimal
#   currencyCode - SOAP::SOAPString
#   deliveryChoice - UKMail::SoapService::Consignment::AddInternationalConsignmentWebRequestDeliveryChoiceType
#   documentsOnly - SOAP::SOAPBoolean
#   extendedCoverRequired - SOAP::SOAPBoolean
#   goodsDescription1 - SOAP::SOAPString
#   goodsDescription2 - SOAP::SOAPString
#   goodsDescription3 - SOAP::SOAPString
#   height - SOAP::SOAPInt
#   inFreeCirculationEU - SOAP::SOAPBoolean
#   invoiceType - UKMail::SoapService::Consignment::InvoiceTypeList
#   length - SOAP::SOAPInt
#   noDangerousGoods - SOAP::SOAPBoolean
#   servicePoint - UKMail::SoapService::Consignment::ServicePointWebModel
#   value - SOAP::SOAPDecimal
#   width - SOAP::SOAPInt
class AddInternationalConsignmentWebRequest < AddConsignmentWebRequest
  attr_accessor :authenticationToken
  attr_accessor :username
  attr_accessor :accountNumber
  attr_accessor :address
  attr_accessor :alternativeRef
  attr_accessor :businessName
  attr_accessor :collectionJobNumber
  attr_accessor :confirmationOfDelivery
  attr_accessor :contactName
  attr_accessor :customersRef
  attr_accessor :email
  attr_accessor :firstMileDropOff
  attr_accessor :items
  attr_accessor :serviceKey
  attr_accessor :specialInstructions1
  attr_accessor :specialInstructions2
  attr_accessor :telephone
  attr_accessor :weight
  attr_accessor :currencyCode
  attr_accessor :deliveryChoice
  attr_accessor :documentsOnly
  attr_accessor :extendedCoverRequired
  attr_accessor :goodsDescription1
  attr_accessor :goodsDescription2
  attr_accessor :goodsDescription3
  attr_accessor :height
  attr_accessor :inFreeCirculationEU
  attr_accessor :invoiceType
  attr_accessor :length
  attr_accessor :noDangerousGoods
  attr_accessor :servicePoint
  attr_accessor :value
  attr_accessor :width

  def initialize(authenticationToken = nil, username = nil, accountNumber = nil, address = nil, alternativeRef = nil, businessName = nil, collectionJobNumber = nil, confirmationOfDelivery = nil, contactName = nil, customersRef = nil, email = nil, firstMileDropOff = nil, items = nil, serviceKey = nil, specialInstructions1 = nil, specialInstructions2 = nil, telephone = nil, weight = nil, currencyCode = nil, deliveryChoice = nil, documentsOnly = nil, extendedCoverRequired = nil, goodsDescription1 = nil, goodsDescription2 = nil, goodsDescription3 = nil, height = nil, inFreeCirculationEU = nil, invoiceType = nil, length = nil, noDangerousGoods = nil, servicePoint = nil, value = nil, width = nil)
    @authenticationToken = authenticationToken
    @username = username
    @accountNumber = accountNumber
    @address = address
    @alternativeRef = alternativeRef
    @businessName = businessName
    @collectionJobNumber = collectionJobNumber
    @confirmationOfDelivery = confirmationOfDelivery
    @contactName = contactName
    @customersRef = customersRef
    @email = email
    @firstMileDropOff = firstMileDropOff
    @items = items
    @serviceKey = serviceKey
    @specialInstructions1 = specialInstructions1
    @specialInstructions2 = specialInstructions2
    @telephone = telephone
    @weight = weight
    @currencyCode = currencyCode
    @deliveryChoice = deliveryChoice
    @documentsOnly = documentsOnly
    @extendedCoverRequired = extendedCoverRequired
    @goodsDescription1 = goodsDescription1
    @goodsDescription2 = goodsDescription2
    @goodsDescription3 = goodsDescription3
    @height = height
    @inFreeCirculationEU = inFreeCirculationEU
    @invoiceType = invoiceType
    @length = length
    @noDangerousGoods = noDangerousGoods
    @servicePoint = servicePoint
    @value = value
    @width = width
  end
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}AddInternationalConsignmentWebRequestV2
#   authenticationToken - SOAP::SOAPString
#   username - SOAP::SOAPString
#   accountNumber - SOAP::SOAPString
#   alternativeReference - SOAP::SOAPString
#   collectionDate - SOAP::SOAPDateTime
#   collectionJobNumber - SOAP::SOAPString
#   currencyCode - SOAP::SOAPString
#   customerReference - SOAP::SOAPString
#   documentsOnly - SOAP::SOAPBoolean
#   emailAddress - SOAP::SOAPString
#   extendedCoverRequired - SOAP::SOAPBoolean
#   firstMileDropOff - SOAP::SOAPBoolean
#   goodsDescription1 - SOAP::SOAPString
#   goodsDescription2 - SOAP::SOAPString
#   goodsDescription3 - SOAP::SOAPString
#   height - SOAP::SOAPInt
#   iOSSNumber - SOAP::SOAPString
#   inboxReturn - SOAP::SOAPBoolean
#   invoiceType - SOAP::SOAPString
#   items - SOAP::SOAPInt
#   labelFormat - SOAP::SOAPString
#   length - SOAP::SOAPInt
#   recipientAddressList - UKMail::SoapService::Consignment::ArrayOfAddress
#   recipientAddressType - SOAP::SOAPString
#   recipientName - SOAP::SOAPString
#   returnAccountNumber - SOAP::SOAPString
#   returnCustomerReference - SOAP::SOAPString
#   serviceKey - SOAP::SOAPString
#   telephoneNumber - SOAP::SOAPString
#   telephoneNumberType - SOAP::SOAPString
#   value - SOAP::SOAPDecimal
#   weight - SOAP::SOAPDecimal
#   width - SOAP::SOAPInt
#   hasIOSS - SOAP::SOAPBoolean
class AddInternationalConsignmentWebRequestV2 < WebRequest
  attr_accessor :authenticationToken
  attr_accessor :username
  attr_accessor :accountNumber
  attr_accessor :alternativeReference
  attr_accessor :collectionDate
  attr_accessor :collectionJobNumber
  attr_accessor :currencyCode
  attr_accessor :customerReference
  attr_accessor :documentsOnly
  attr_accessor :emailAddress
  attr_accessor :extendedCoverRequired
  attr_accessor :firstMileDropOff
  attr_accessor :goodsDescription1
  attr_accessor :goodsDescription2
  attr_accessor :goodsDescription3
  attr_accessor :height
  attr_accessor :iOSSNumber
  attr_accessor :inboxReturn
  attr_accessor :invoiceType
  attr_accessor :items
  attr_accessor :labelFormat
  attr_accessor :length
  attr_accessor :recipientAddressList
  attr_accessor :recipientAddressType
  attr_accessor :recipientName
  attr_accessor :returnAccountNumber
  attr_accessor :returnCustomerReference
  attr_accessor :serviceKey
  attr_accessor :telephoneNumber
  attr_accessor :telephoneNumberType
  attr_accessor :value
  attr_accessor :weight
  attr_accessor :width
  attr_accessor :hasIOSS

  def initialize(authenticationToken = nil, username = nil, accountNumber = nil, alternativeReference = nil, collectionDate = nil, collectionJobNumber = nil, currencyCode = nil, customerReference = nil, documentsOnly = nil, emailAddress = nil, extendedCoverRequired = nil, firstMileDropOff = nil, goodsDescription1 = nil, goodsDescription2 = nil, goodsDescription3 = nil, height = nil, iOSSNumber = nil, inboxReturn = nil, invoiceType = nil, items = nil, labelFormat = nil, length = nil, recipientAddressList = nil, recipientAddressType = nil, recipientName = nil, returnAccountNumber = nil, returnCustomerReference = nil, serviceKey = nil, telephoneNumber = nil, telephoneNumberType = nil, value = nil, weight = nil, width = nil, hasIOSS = nil)
    @authenticationToken = authenticationToken
    @username = username
    @accountNumber = accountNumber
    @alternativeReference = alternativeReference
    @collectionDate = collectionDate
    @collectionJobNumber = collectionJobNumber
    @currencyCode = currencyCode
    @customerReference = customerReference
    @documentsOnly = documentsOnly
    @emailAddress = emailAddress
    @extendedCoverRequired = extendedCoverRequired
    @firstMileDropOff = firstMileDropOff
    @goodsDescription1 = goodsDescription1
    @goodsDescription2 = goodsDescription2
    @goodsDescription3 = goodsDescription3
    @height = height
    @iOSSNumber = iOSSNumber
    @inboxReturn = inboxReturn
    @invoiceType = invoiceType
    @items = items
    @labelFormat = labelFormat
    @length = length
    @recipientAddressList = recipientAddressList
    @recipientAddressType = recipientAddressType
    @recipientName = recipientName
    @returnAccountNumber = returnAccountNumber
    @returnCustomerReference = returnCustomerReference
    @serviceKey = serviceKey
    @telephoneNumber = telephoneNumber
    @telephoneNumberType = telephoneNumberType
    @value = value
    @weight = weight
    @width = width
    @hasIOSS = hasIOSS
  end
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}AddInternationalConsignmentWebRequestV3
#   authenticationToken - SOAP::SOAPString
#   username - SOAP::SOAPString
#   accountNumber - SOAP::SOAPString
#   alternativeReference - SOAP::SOAPString
#   collectionDate - SOAP::SOAPDateTime
#   collectionJobNumber - SOAP::SOAPString
#   currencyCode - SOAP::SOAPString
#   customerReference - SOAP::SOAPString
#   documentsOnly - SOAP::SOAPBoolean
#   emailAddress - SOAP::SOAPString
#   extendedCoverRequired - SOAP::SOAPBoolean
#   firstMileDropOff - SOAP::SOAPBoolean
#   goodsDescription1 - SOAP::SOAPString
#   goodsDescription2 - SOAP::SOAPString
#   goodsDescription3 - SOAP::SOAPString
#   height - SOAP::SOAPInt
#   iOSSNumber - SOAP::SOAPString
#   inboxReturn - SOAP::SOAPBoolean
#   invoiceType - SOAP::SOAPString
#   items - SOAP::SOAPInt
#   labelFormat - SOAP::SOAPString
#   length - SOAP::SOAPInt
#   recipientAddressList - UKMail::SoapService::Consignment::ArrayOfAddress
#   recipientAddressType - SOAP::SOAPString
#   recipientName - SOAP::SOAPString
#   returnAccountNumber - SOAP::SOAPString
#   returnCustomerReference - SOAP::SOAPString
#   serviceKey - SOAP::SOAPString
#   telephoneNumber - SOAP::SOAPString
#   telephoneNumberType - SOAP::SOAPString
#   value - SOAP::SOAPDecimal
#   weight - SOAP::SOAPDecimal
#   width - SOAP::SOAPInt
#   hasIOSS - SOAP::SOAPBoolean
#   basicCustoms - SOAP::SOAPBoolean
#   customsDeclaration - UKMail::SoapService::Consignment::CustomsDeclaration
#   fullCustoms - SOAP::SOAPBoolean
#   invoiceRequired - SOAP::SOAPBoolean
#   recipient - UKMail::SoapService::Consignment::Recipient
class AddInternationalConsignmentWebRequestV3 < AddInternationalConsignmentWebRequestV2
  attr_accessor :authenticationToken
  attr_accessor :username
  attr_accessor :accountNumber
  attr_accessor :alternativeReference
  attr_accessor :collectionDate
  attr_accessor :collectionJobNumber
  attr_accessor :currencyCode
  attr_accessor :customerReference
  attr_accessor :documentsOnly
  attr_accessor :emailAddress
  attr_accessor :extendedCoverRequired
  attr_accessor :firstMileDropOff
  attr_accessor :goodsDescription1
  attr_accessor :goodsDescription2
  attr_accessor :goodsDescription3
  attr_accessor :height
  attr_accessor :iOSSNumber
  attr_accessor :inboxReturn
  attr_accessor :invoiceType
  attr_accessor :items
  attr_accessor :labelFormat
  attr_accessor :length
  attr_accessor :recipientAddressList
  attr_accessor :recipientAddressType
  attr_accessor :recipientName
  attr_accessor :returnAccountNumber
  attr_accessor :returnCustomerReference
  attr_accessor :serviceKey
  attr_accessor :telephoneNumber
  attr_accessor :telephoneNumberType
  attr_accessor :value
  attr_accessor :weight
  attr_accessor :width
  attr_accessor :hasIOSS
  attr_accessor :basicCustoms
  attr_accessor :customsDeclaration
  attr_accessor :fullCustoms
  attr_accessor :invoiceRequired
  attr_accessor :recipient

  def initialize(authenticationToken = nil, username = nil, accountNumber = nil, alternativeReference = nil, collectionDate = nil, collectionJobNumber = nil, currencyCode = nil, customerReference = nil, documentsOnly = nil, emailAddress = nil, extendedCoverRequired = nil, firstMileDropOff = nil, goodsDescription1 = nil, goodsDescription2 = nil, goodsDescription3 = nil, height = nil, iOSSNumber = nil, inboxReturn = nil, invoiceType = nil, items = nil, labelFormat = nil, length = nil, recipientAddressList = nil, recipientAddressType = nil, recipientName = nil, returnAccountNumber = nil, returnCustomerReference = nil, serviceKey = nil, telephoneNumber = nil, telephoneNumberType = nil, value = nil, weight = nil, width = nil, hasIOSS = nil, basicCustoms = nil, customsDeclaration = nil, fullCustoms = nil, invoiceRequired = nil, recipient = nil)
    @authenticationToken = authenticationToken
    @username = username
    @accountNumber = accountNumber
    @alternativeReference = alternativeReference
    @collectionDate = collectionDate
    @collectionJobNumber = collectionJobNumber
    @currencyCode = currencyCode
    @customerReference = customerReference
    @documentsOnly = documentsOnly
    @emailAddress = emailAddress
    @extendedCoverRequired = extendedCoverRequired
    @firstMileDropOff = firstMileDropOff
    @goodsDescription1 = goodsDescription1
    @goodsDescription2 = goodsDescription2
    @goodsDescription3 = goodsDescription3
    @height = height
    @iOSSNumber = iOSSNumber
    @inboxReturn = inboxReturn
    @invoiceType = invoiceType
    @items = items
    @labelFormat = labelFormat
    @length = length
    @recipientAddressList = recipientAddressList
    @recipientAddressType = recipientAddressType
    @recipientName = recipientName
    @returnAccountNumber = returnAccountNumber
    @returnCustomerReference = returnCustomerReference
    @serviceKey = serviceKey
    @telephoneNumber = telephoneNumber
    @telephoneNumberType = telephoneNumberType
    @value = value
    @weight = weight
    @width = width
    @hasIOSS = hasIOSS
    @basicCustoms = basicCustoms
    @customsDeclaration = customsDeclaration
    @fullCustoms = fullCustoms
    @invoiceRequired = invoiceRequired
    @recipient = recipient
  end
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}AddReturnWebRequest
#   authenticationToken - SOAP::SOAPString
#   username - SOAP::SOAPString
#   accountNumber - SOAP::SOAPString
#   bookIn - SOAP::SOAPBoolean
#   collectionAddress - UKMail::SoapService::Consignment::AddressWebModel
#   collectionBusinessName - SOAP::SOAPString
#   collectionContactName - SOAP::SOAPString
#   collectionCustomersRef - SOAP::SOAPString
#   collectionDate - SOAP::SOAPDateTime
#   collectionEmail - SOAP::SOAPString
#   collectionLatestPickup - SOAP::SOAPDateTime
#   collectionOpenLunchtime - SOAP::SOAPBoolean
#   collectionSpecialInstructions1 - SOAP::SOAPString
#   collectionSpecialInstructions2 - SOAP::SOAPString
#   collectionTelephone - SOAP::SOAPString
#   collectionTimeReady - SOAP::SOAPDateTime
#   deliverySpecialInstructions1 - SOAP::SOAPString
#   deliverySpecialInstructions2 - SOAP::SOAPString
#   descriptionOfGoods1 - SOAP::SOAPString
#   descriptionOfGoods2 - SOAP::SOAPString
#   serviceKey - SOAP::SOAPInt
#   clearance - UKMail::SoapService::Consignment::Clearance
class AddReturnWebRequest < WebRequest
  attr_accessor :authenticationToken
  attr_accessor :username
  attr_accessor :accountNumber
  attr_accessor :bookIn
  attr_accessor :collectionAddress
  attr_accessor :collectionBusinessName
  attr_accessor :collectionContactName
  attr_accessor :collectionCustomersRef
  attr_accessor :collectionDate
  attr_accessor :collectionEmail
  attr_accessor :collectionLatestPickup
  attr_accessor :collectionOpenLunchtime
  attr_accessor :collectionSpecialInstructions1
  attr_accessor :collectionSpecialInstructions2
  attr_accessor :collectionTelephone
  attr_accessor :collectionTimeReady
  attr_accessor :deliverySpecialInstructions1
  attr_accessor :deliverySpecialInstructions2
  attr_accessor :descriptionOfGoods1
  attr_accessor :descriptionOfGoods2
  attr_accessor :serviceKey
  attr_accessor :clearance

  def initialize(authenticationToken = nil, username = nil, accountNumber = nil, bookIn = nil, collectionAddress = nil, collectionBusinessName = nil, collectionContactName = nil, collectionCustomersRef = nil, collectionDate = nil, collectionEmail = nil, collectionLatestPickup = nil, collectionOpenLunchtime = nil, collectionSpecialInstructions1 = nil, collectionSpecialInstructions2 = nil, collectionTelephone = nil, collectionTimeReady = nil, deliverySpecialInstructions1 = nil, deliverySpecialInstructions2 = nil, descriptionOfGoods1 = nil, descriptionOfGoods2 = nil, serviceKey = nil, clearance = nil)
    @authenticationToken = authenticationToken
    @username = username
    @accountNumber = accountNumber
    @bookIn = bookIn
    @collectionAddress = collectionAddress
    @collectionBusinessName = collectionBusinessName
    @collectionContactName = collectionContactName
    @collectionCustomersRef = collectionCustomersRef
    @collectionDate = collectionDate
    @collectionEmail = collectionEmail
    @collectionLatestPickup = collectionLatestPickup
    @collectionOpenLunchtime = collectionOpenLunchtime
    @collectionSpecialInstructions1 = collectionSpecialInstructions1
    @collectionSpecialInstructions2 = collectionSpecialInstructions2
    @collectionTelephone = collectionTelephone
    @collectionTimeReady = collectionTimeReady
    @deliverySpecialInstructions1 = deliverySpecialInstructions1
    @deliverySpecialInstructions2 = deliverySpecialInstructions2
    @descriptionOfGoods1 = descriptionOfGoods1
    @descriptionOfGoods2 = descriptionOfGoods2
    @serviceKey = serviceKey
    @clearance = clearance
  end
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}AddSendToThirdPartyWebRequest
#   authenticationToken - SOAP::SOAPString
#   username - SOAP::SOAPString
#   accountNumber - SOAP::SOAPString
#   bookIn - SOAP::SOAPBoolean
#   collectionAddress - UKMail::SoapService::Consignment::AddressWebModel
#   collectionBusinessName - SOAP::SOAPString
#   collectionContactName - SOAP::SOAPString
#   collectionCustomersRef - SOAP::SOAPString
#   collectionDate - SOAP::SOAPDateTime
#   collectionEmail - SOAP::SOAPString
#   collectionLatestPickup - SOAP::SOAPDateTime
#   collectionOpenLunchtime - SOAP::SOAPBoolean
#   collectionSpecialInstructions1 - SOAP::SOAPString
#   collectionSpecialInstructions2 - SOAP::SOAPString
#   collectionTelephone - SOAP::SOAPString
#   collectionTimeReady - SOAP::SOAPDateTime
#   deliverySpecialInstructions1 - SOAP::SOAPString
#   deliverySpecialInstructions2 - SOAP::SOAPString
#   descriptionOfGoods1 - SOAP::SOAPString
#   descriptionOfGoods2 - SOAP::SOAPString
#   serviceKey - SOAP::SOAPInt
#   clearance - UKMail::SoapService::Consignment::Clearance
#   deliveryContactName - SOAP::SOAPString
#   deliveryBusinessName - SOAP::SOAPString
#   deliveryAddress - UKMail::SoapService::Consignment::AddressWebModel
#   deliveryTelephone - SOAP::SOAPString
#   deliveryEmail - SOAP::SOAPString
class AddSendToThirdPartyWebRequest < AddReturnWebRequest
  attr_accessor :authenticationToken
  attr_accessor :username
  attr_accessor :accountNumber
  attr_accessor :bookIn
  attr_accessor :collectionAddress
  attr_accessor :collectionBusinessName
  attr_accessor :collectionContactName
  attr_accessor :collectionCustomersRef
  attr_accessor :collectionDate
  attr_accessor :collectionEmail
  attr_accessor :collectionLatestPickup
  attr_accessor :collectionOpenLunchtime
  attr_accessor :collectionSpecialInstructions1
  attr_accessor :collectionSpecialInstructions2
  attr_accessor :collectionTelephone
  attr_accessor :collectionTimeReady
  attr_accessor :deliverySpecialInstructions1
  attr_accessor :deliverySpecialInstructions2
  attr_accessor :descriptionOfGoods1
  attr_accessor :descriptionOfGoods2
  attr_accessor :serviceKey
  attr_accessor :clearance
  attr_accessor :deliveryContactName
  attr_accessor :deliveryBusinessName
  attr_accessor :deliveryAddress
  attr_accessor :deliveryTelephone
  attr_accessor :deliveryEmail

  def initialize(authenticationToken = nil, username = nil, accountNumber = nil, bookIn = nil, collectionAddress = nil, collectionBusinessName = nil, collectionContactName = nil, collectionCustomersRef = nil, collectionDate = nil, collectionEmail = nil, collectionLatestPickup = nil, collectionOpenLunchtime = nil, collectionSpecialInstructions1 = nil, collectionSpecialInstructions2 = nil, collectionTelephone = nil, collectionTimeReady = nil, deliverySpecialInstructions1 = nil, deliverySpecialInstructions2 = nil, descriptionOfGoods1 = nil, descriptionOfGoods2 = nil, serviceKey = nil, clearance = nil, deliveryContactName = nil, deliveryBusinessName = nil, deliveryAddress = nil, deliveryTelephone = nil, deliveryEmail = nil)
    @authenticationToken = authenticationToken
    @username = username
    @accountNumber = accountNumber
    @bookIn = bookIn
    @collectionAddress = collectionAddress
    @collectionBusinessName = collectionBusinessName
    @collectionContactName = collectionContactName
    @collectionCustomersRef = collectionCustomersRef
    @collectionDate = collectionDate
    @collectionEmail = collectionEmail
    @collectionLatestPickup = collectionLatestPickup
    @collectionOpenLunchtime = collectionOpenLunchtime
    @collectionSpecialInstructions1 = collectionSpecialInstructions1
    @collectionSpecialInstructions2 = collectionSpecialInstructions2
    @collectionTelephone = collectionTelephone
    @collectionTimeReady = collectionTimeReady
    @deliverySpecialInstructions1 = deliverySpecialInstructions1
    @deliverySpecialInstructions2 = deliverySpecialInstructions2
    @descriptionOfGoods1 = descriptionOfGoods1
    @descriptionOfGoods2 = descriptionOfGoods2
    @serviceKey = serviceKey
    @clearance = clearance
    @deliveryContactName = deliveryContactName
    @deliveryBusinessName = deliveryBusinessName
    @deliveryAddress = deliveryAddress
    @deliveryTelephone = deliveryTelephone
    @deliveryEmail = deliveryEmail
  end
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}CancelConsignmentWebRequest
#   authenticationToken - SOAP::SOAPString
#   username - SOAP::SOAPString
#   consignmentNumber - SOAP::SOAPString
class CancelConsignmentWebRequest < WebRequest
  attr_accessor :authenticationToken
  attr_accessor :username
  attr_accessor :consignmentNumber

  def initialize(authenticationToken = nil, username = nil, consignmentNumber = nil)
    @authenticationToken = authenticationToken
    @username = username
    @consignmentNumber = consignmentNumber
  end
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}CancelReturnWebRequest
#   authenticationToken - SOAP::SOAPString
#   username - SOAP::SOAPString
#   consignmentNumber - SOAP::SOAPString
class CancelReturnWebRequest < WebRequest
  attr_accessor :authenticationToken
  attr_accessor :username
  attr_accessor :consignmentNumber

  def initialize(authenticationToken = nil, username = nil, consignmentNumber = nil)
    @authenticationToken = authenticationToken
    @username = username
    @consignmentNumber = consignmentNumber
  end
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}AddConsignmentDeferredWebRequest
#   authenticationToken - SOAP::SOAPString
#   username - SOAP::SOAPString
#   accountNumber - SOAP::SOAPString
#   address - UKMail::SoapService::Consignment::AddressWebModel
#   alternativeRef - SOAP::SOAPString
#   businessName - SOAP::SOAPString
#   collectionDate - SOAP::SOAPDateTime
#   confirmationOfDelivery - SOAP::SOAPBoolean
#   contactName - SOAP::SOAPString
#   customersRef - SOAP::SOAPString
#   email - SOAP::SOAPString
#   items - SOAP::SOAPInt
#   labelFormat - UKMail::SoapService::Consignment::LabelFormatType
#   serviceKey - SOAP::SOAPInt
#   specialInstructions1 - SOAP::SOAPString
#   specialInstructions2 - SOAP::SOAPString
#   telephone - SOAP::SOAPString
#   weight - SOAP::SOAPDecimal
class AddConsignmentDeferredWebRequest < WebRequest
  attr_accessor :authenticationToken
  attr_accessor :username
  attr_accessor :accountNumber
  attr_accessor :address
  attr_accessor :alternativeRef
  attr_accessor :businessName
  attr_accessor :collectionDate
  attr_accessor :confirmationOfDelivery
  attr_accessor :contactName
  attr_accessor :customersRef
  attr_accessor :email
  attr_accessor :items
  attr_accessor :labelFormat
  attr_accessor :serviceKey
  attr_accessor :specialInstructions1
  attr_accessor :specialInstructions2
  attr_accessor :telephone
  attr_accessor :weight

  def initialize(authenticationToken = nil, username = nil, accountNumber = nil, address = nil, alternativeRef = nil, businessName = nil, collectionDate = nil, confirmationOfDelivery = nil, contactName = nil, customersRef = nil, email = nil, items = nil, labelFormat = nil, serviceKey = nil, specialInstructions1 = nil, specialInstructions2 = nil, telephone = nil, weight = nil)
    @authenticationToken = authenticationToken
    @username = username
    @accountNumber = accountNumber
    @address = address
    @alternativeRef = alternativeRef
    @businessName = businessName
    @collectionDate = collectionDate
    @confirmationOfDelivery = confirmationOfDelivery
    @contactName = contactName
    @customersRef = customersRef
    @email = email
    @items = items
    @labelFormat = labelFormat
    @serviceKey = serviceKey
    @specialInstructions1 = specialInstructions1
    @specialInstructions2 = specialInstructions2
    @telephone = telephone
    @weight = weight
  end
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}AddDomesticConsignmentDeferredWebRequest
#   authenticationToken - SOAP::SOAPString
#   username - SOAP::SOAPString
#   accountNumber - SOAP::SOAPString
#   address - UKMail::SoapService::Consignment::AddressWebModel
#   alternativeRef - SOAP::SOAPString
#   businessName - SOAP::SOAPString
#   collectionDate - SOAP::SOAPDateTime
#   confirmationOfDelivery - SOAP::SOAPBoolean
#   contactName - SOAP::SOAPString
#   customersRef - SOAP::SOAPString
#   email - SOAP::SOAPString
#   items - SOAP::SOAPInt
#   labelFormat - UKMail::SoapService::Consignment::LabelFormatType
#   serviceKey - SOAP::SOAPInt
#   specialInstructions1 - SOAP::SOAPString
#   specialInstructions2 - SOAP::SOAPString
#   telephone - SOAP::SOAPString
#   weight - SOAP::SOAPDecimal
#   bookIn - SOAP::SOAPBoolean
#   cODAmount - SOAP::SOAPDecimal
#   confirmationEmail - SOAP::SOAPString
#   confirmationTelephone - SOAP::SOAPString
#   exchangeOnDelivery - SOAP::SOAPBoolean
#   extendedCover - SOAP::SOAPInt
#   longLength - SOAP::SOAPBoolean
#   preDeliveryNotification - UKMail::SoapService::Consignment::PreDeliveryNotificationType
#   secureLocation1 - SOAP::SOAPString
#   secureLocation2 - SOAP::SOAPString
#   signatureOptional - SOAP::SOAPBoolean
class AddDomesticConsignmentDeferredWebRequest < AddConsignmentDeferredWebRequest
  attr_accessor :authenticationToken
  attr_accessor :username
  attr_accessor :accountNumber
  attr_accessor :address
  attr_accessor :alternativeRef
  attr_accessor :businessName
  attr_accessor :collectionDate
  attr_accessor :confirmationOfDelivery
  attr_accessor :contactName
  attr_accessor :customersRef
  attr_accessor :email
  attr_accessor :items
  attr_accessor :labelFormat
  attr_accessor :serviceKey
  attr_accessor :specialInstructions1
  attr_accessor :specialInstructions2
  attr_accessor :telephone
  attr_accessor :weight
  attr_accessor :bookIn
  attr_accessor :cODAmount
  attr_accessor :confirmationEmail
  attr_accessor :confirmationTelephone
  attr_accessor :exchangeOnDelivery
  attr_accessor :extendedCover
  attr_accessor :longLength
  attr_accessor :preDeliveryNotification
  attr_accessor :secureLocation1
  attr_accessor :secureLocation2
  attr_accessor :signatureOptional

  def initialize(authenticationToken = nil, username = nil, accountNumber = nil, address = nil, alternativeRef = nil, businessName = nil, collectionDate = nil, confirmationOfDelivery = nil, contactName = nil, customersRef = nil, email = nil, items = nil, labelFormat = nil, serviceKey = nil, specialInstructions1 = nil, specialInstructions2 = nil, telephone = nil, weight = nil, bookIn = nil, cODAmount = nil, confirmationEmail = nil, confirmationTelephone = nil, exchangeOnDelivery = nil, extendedCover = nil, longLength = nil, preDeliveryNotification = nil, secureLocation1 = nil, secureLocation2 = nil, signatureOptional = nil)
    @authenticationToken = authenticationToken
    @username = username
    @accountNumber = accountNumber
    @address = address
    @alternativeRef = alternativeRef
    @businessName = businessName
    @collectionDate = collectionDate
    @confirmationOfDelivery = confirmationOfDelivery
    @contactName = contactName
    @customersRef = customersRef
    @email = email
    @items = items
    @labelFormat = labelFormat
    @serviceKey = serviceKey
    @specialInstructions1 = specialInstructions1
    @specialInstructions2 = specialInstructions2
    @telephone = telephone
    @weight = weight
    @bookIn = bookIn
    @cODAmount = cODAmount
    @confirmationEmail = confirmationEmail
    @confirmationTelephone = confirmationTelephone
    @exchangeOnDelivery = exchangeOnDelivery
    @extendedCover = extendedCover
    @longLength = longLength
    @preDeliveryNotification = preDeliveryNotification
    @secureLocation1 = secureLocation1
    @secureLocation2 = secureLocation2
    @signatureOptional = signatureOptional
  end
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}AddDomesticConsignmentDeferredWebRequestV2
#   authenticationToken - SOAP::SOAPString
#   username - SOAP::SOAPString
#   accountNumber - SOAP::SOAPString
#   address - UKMail::SoapService::Consignment::AddressWebModel
#   alternativeRef - SOAP::SOAPString
#   businessName - SOAP::SOAPString
#   collectionDate - SOAP::SOAPDateTime
#   confirmationOfDelivery - SOAP::SOAPBoolean
#   contactName - SOAP::SOAPString
#   customersRef - SOAP::SOAPString
#   email - SOAP::SOAPString
#   items - SOAP::SOAPInt
#   labelFormat - UKMail::SoapService::Consignment::LabelFormatType
#   serviceKey - SOAP::SOAPInt
#   specialInstructions1 - SOAP::SOAPString
#   specialInstructions2 - SOAP::SOAPString
#   telephone - SOAP::SOAPString
#   weight - SOAP::SOAPDecimal
#   bookIn - SOAP::SOAPBoolean
#   cODAmount - SOAP::SOAPDecimal
#   confirmationEmail - SOAP::SOAPString
#   confirmationTelephone - SOAP::SOAPString
#   exchangeOnDelivery - SOAP::SOAPBoolean
#   extendedCover - SOAP::SOAPInt
#   longLength - SOAP::SOAPBoolean
#   preDeliveryNotification - UKMail::SoapService::Consignment::PreDeliveryNotificationType
#   secureLocation1 - SOAP::SOAPString
#   secureLocation2 - SOAP::SOAPString
#   signatureOptional - SOAP::SOAPBoolean
#   basicCustomsDeclaration - UKMail::SoapService::Consignment::BasicCustomsDeclaration
#   fullCustomsDeclaration - UKMail::SoapService::Consignment::CustomsDeclaration
class AddDomesticConsignmentDeferredWebRequestV2 < AddDomesticConsignmentDeferredWebRequest
  attr_accessor :authenticationToken
  attr_accessor :username
  attr_accessor :accountNumber
  attr_accessor :address
  attr_accessor :alternativeRef
  attr_accessor :businessName
  attr_accessor :collectionDate
  attr_accessor :confirmationOfDelivery
  attr_accessor :contactName
  attr_accessor :customersRef
  attr_accessor :email
  attr_accessor :items
  attr_accessor :labelFormat
  attr_accessor :serviceKey
  attr_accessor :specialInstructions1
  attr_accessor :specialInstructions2
  attr_accessor :telephone
  attr_accessor :weight
  attr_accessor :bookIn
  attr_accessor :cODAmount
  attr_accessor :confirmationEmail
  attr_accessor :confirmationTelephone
  attr_accessor :exchangeOnDelivery
  attr_accessor :extendedCover
  attr_accessor :longLength
  attr_accessor :preDeliveryNotification
  attr_accessor :secureLocation1
  attr_accessor :secureLocation2
  attr_accessor :signatureOptional
  attr_accessor :basicCustomsDeclaration
  attr_accessor :fullCustomsDeclaration

  def initialize(authenticationToken = nil, username = nil, accountNumber = nil, address = nil, alternativeRef = nil, businessName = nil, collectionDate = nil, confirmationOfDelivery = nil, contactName = nil, customersRef = nil, email = nil, items = nil, labelFormat = nil, serviceKey = nil, specialInstructions1 = nil, specialInstructions2 = nil, telephone = nil, weight = nil, bookIn = nil, cODAmount = nil, confirmationEmail = nil, confirmationTelephone = nil, exchangeOnDelivery = nil, extendedCover = nil, longLength = nil, preDeliveryNotification = nil, secureLocation1 = nil, secureLocation2 = nil, signatureOptional = nil, basicCustomsDeclaration = nil, fullCustomsDeclaration = nil)
    @authenticationToken = authenticationToken
    @username = username
    @accountNumber = accountNumber
    @address = address
    @alternativeRef = alternativeRef
    @businessName = businessName
    @collectionDate = collectionDate
    @confirmationOfDelivery = confirmationOfDelivery
    @contactName = contactName
    @customersRef = customersRef
    @email = email
    @items = items
    @labelFormat = labelFormat
    @serviceKey = serviceKey
    @specialInstructions1 = specialInstructions1
    @specialInstructions2 = specialInstructions2
    @telephone = telephone
    @weight = weight
    @bookIn = bookIn
    @cODAmount = cODAmount
    @confirmationEmail = confirmationEmail
    @confirmationTelephone = confirmationTelephone
    @exchangeOnDelivery = exchangeOnDelivery
    @extendedCover = extendedCover
    @longLength = longLength
    @preDeliveryNotification = preDeliveryNotification
    @secureLocation1 = secureLocation1
    @secureLocation2 = secureLocation2
    @signatureOptional = signatureOptional
    @basicCustomsDeclaration = basicCustomsDeclaration
    @fullCustomsDeclaration = fullCustomsDeclaration
  end
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}ArrayOfAddress
class ArrayOfAddress < ::Array
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}Address
#   address1 - SOAP::SOAPString
#   address2 - SOAP::SOAPString
#   address3 - SOAP::SOAPString
#   addressType - SOAP::SOAPString
#   businessName - SOAP::SOAPString
#   county - SOAP::SOAPString
#   postalTown - SOAP::SOAPString
#   threeDigitCountryCode - SOAP::SOAPString
#   zipcode - SOAP::SOAPString
class Address
  attr_accessor :address1
  attr_accessor :address2
  attr_accessor :address3
  attr_accessor :addressType
  attr_accessor :businessName
  attr_accessor :county
  attr_accessor :postalTown
  attr_accessor :threeDigitCountryCode
  attr_accessor :zipcode

  def initialize(address1 = nil, address2 = nil, address3 = nil, addressType = nil, businessName = nil, county = nil, postalTown = nil, threeDigitCountryCode = nil, zipcode = nil)
    @address1 = address1
    @address2 = address2
    @address3 = address3
    @addressType = addressType
    @businessName = businessName
    @county = county
    @postalTown = postalTown
    @threeDigitCountryCode = threeDigitCountryCode
    @zipcode = zipcode
  end
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}Clearance
#   shipmentMovementType - SOAP::SOAPString
#   senderEORINumber - SOAP::SOAPString
#   senderUKIMSNumber - SOAP::SOAPString
#   recipientEORINumber - SOAP::SOAPString
#   senderDefermentAccount - SOAP::SOAPString
#   recipientUKIMSNumber - SOAP::SOAPString
#   numberOfPieces - SOAP::SOAPInt
#   shippingCharges - SOAP::SOAPDecimal
#   totalValue - SOAP::SOAPDecimal
#   reasonForExport - SOAP::SOAPString
#   clearanceItems - UKMail::SoapService::Consignment::ArrayOfClearanceItem
class Clearance
  attr_accessor :shipmentMovementType
  attr_accessor :senderEORINumber
  attr_accessor :senderUKIMSNumber
  attr_accessor :recipientEORINumber
  attr_accessor :senderDefermentAccount
  attr_accessor :recipientUKIMSNumber
  attr_accessor :numberOfPieces
  attr_accessor :shippingCharges
  attr_accessor :totalValue
  attr_accessor :reasonForExport
  attr_accessor :clearanceItems

  def initialize(shipmentMovementType = nil, senderEORINumber = nil, senderUKIMSNumber = nil, recipientEORINumber = nil, senderDefermentAccount = nil, recipientUKIMSNumber = nil, numberOfPieces = nil, shippingCharges = nil, totalValue = nil, reasonForExport = nil, clearanceItems = nil)
    @shipmentMovementType = shipmentMovementType
    @senderEORINumber = senderEORINumber
    @senderUKIMSNumber = senderUKIMSNumber
    @recipientEORINumber = recipientEORINumber
    @senderDefermentAccount = senderDefermentAccount
    @recipientUKIMSNumber = recipientUKIMSNumber
    @numberOfPieces = numberOfPieces
    @shippingCharges = shippingCharges
    @totalValue = totalValue
    @reasonForExport = reasonForExport
    @clearanceItems = clearanceItems
  end
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}ArrayOfClearanceItem
class ArrayOfClearanceItem < ::Array
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}ClearanceItem
#   commodityCode - SOAP::SOAPString
#   goodsDescription - SOAP::SOAPString
#   unitQuantity - SOAP::SOAPInt
#   unitValue - SOAP::SOAPDecimal
#   unitWeight - SOAP::SOAPFloat
#   countryofManufacture - SOAP::SOAPString
class ClearanceItem
  attr_accessor :commodityCode
  attr_accessor :goodsDescription
  attr_accessor :unitQuantity
  attr_accessor :unitValue
  attr_accessor :unitWeight
  attr_accessor :countryofManufacture

  def initialize(commodityCode = nil, goodsDescription = nil, unitQuantity = nil, unitValue = nil, unitWeight = nil, countryofManufacture = nil)
    @commodityCode = commodityCode
    @goodsDescription = goodsDescription
    @unitQuantity = unitQuantity
    @unitValue = unitValue
    @unitWeight = unitWeight
    @countryofManufacture = countryofManufacture
  end
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}BasicCustomsDeclaration
#   currencyCode - SOAP::SOAPString
#   descriptionOfGoods - SOAP::SOAPString
#   documentsOnly - SOAP::SOAPBoolean
#   invoiceType - UKMail::SoapService::Consignment::InvoiceType
#   value - SOAP::SOAPDecimal
class BasicCustomsDeclaration
  attr_accessor :currencyCode
  attr_accessor :descriptionOfGoods
  attr_accessor :documentsOnly
  attr_accessor :invoiceType
  attr_accessor :value

  def initialize(currencyCode = nil, descriptionOfGoods = nil, documentsOnly = nil, invoiceType = nil, value = nil)
    @currencyCode = currencyCode
    @descriptionOfGoods = descriptionOfGoods
    @documentsOnly = documentsOnly
    @invoiceType = invoiceType
    @value = value
  end
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}UKMWebResponseV2
#   errors - UKMail::SoapService::Consignment::ArrayOfUKMWebError
#   result - UKMail::SoapService::Consignment::UKMResultState
#   warnings - UKMail::SoapService::Consignment::ArrayOfUKMWebWarning
class UKMWebResponseV2
  attr_accessor :errors
  attr_accessor :result
  attr_accessor :warnings

  def initialize(errors = nil, result = nil, warnings = nil)
    @errors = errors
    @result = result
    @warnings = warnings
  end
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}UKMAddDomesticConsignmentWebResponseV2
#   errors - UKMail::SoapService::Consignment::ArrayOfUKMWebError
#   result - UKMail::SoapService::Consignment::UKMResultState
#   warnings - UKMail::SoapService::Consignment::ArrayOfUKMWebWarning
#   consignmentId - SOAP::SOAPLong
#   consignmentNumber - SOAP::SOAPString
#   labels - UKMail::SoapService::Consignment::ArrayOfbase64Binary
#   returnConsignmentNumber - SOAP::SOAPString
class UKMAddDomesticConsignmentWebResponseV2 < UKMWebResponseV2
  attr_accessor :errors
  attr_accessor :result
  attr_accessor :warnings
  attr_accessor :consignmentId
  attr_accessor :consignmentNumber
  attr_accessor :labels
  attr_accessor :returnConsignmentNumber

  def initialize(errors = nil, result = nil, warnings = nil, consignmentId = nil, consignmentNumber = nil, labels = nil, returnConsignmentNumber = nil)
    @errors = errors
    @result = result
    @warnings = warnings
    @consignmentId = consignmentId
    @consignmentNumber = consignmentNumber
    @labels = labels
    @returnConsignmentNumber = returnConsignmentNumber
  end
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}UKMAddInternationalConsignmentWebResponseV2
#   errors - UKMail::SoapService::Consignment::ArrayOfUKMWebError
#   result - UKMail::SoapService::Consignment::UKMResultState
#   warnings - UKMail::SoapService::Consignment::ArrayOfUKMWebWarning
#   consignmentNumber - SOAP::SOAPString
#   invoiceBytes - SOAP::SOAPBase64
#   labels - UKMail::SoapService::Consignment::ArrayOfbase64Binary
#   returnConsignmentNumber - SOAP::SOAPString
class UKMAddInternationalConsignmentWebResponseV2 < UKMWebResponseV2
  attr_accessor :errors
  attr_accessor :result
  attr_accessor :warnings
  attr_accessor :consignmentNumber
  attr_accessor :invoiceBytes
  attr_accessor :labels
  attr_accessor :returnConsignmentNumber

  def initialize(errors = nil, result = nil, warnings = nil, consignmentNumber = nil, invoiceBytes = nil, labels = nil, returnConsignmentNumber = nil)
    @errors = errors
    @result = result
    @warnings = warnings
    @consignmentNumber = consignmentNumber
    @invoiceBytes = invoiceBytes
    @labels = labels
    @returnConsignmentNumber = returnConsignmentNumber
  end
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}ArrayOfUKMWebError
class ArrayOfUKMWebError < ::Array
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}UKMWebError
#   code - SOAP::SOAPInt
#   description - SOAP::SOAPString
class UKMWebError
  attr_accessor :code
  attr_accessor :description

  def initialize(code = nil, description = nil)
    @code = code
    @description = description
  end
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}ArrayOfUKMWebWarning
class ArrayOfUKMWebWarning < ::Array
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}UKMWebWarning
#   code - SOAP::SOAPInt
#   description - SOAP::SOAPString
class UKMWebWarning
  attr_accessor :code
  attr_accessor :description

  def initialize(code = nil, description = nil)
    @code = code
    @description = description
  end
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}AddressWebModel
#   address1 - SOAP::SOAPString
#   address2 - SOAP::SOAPString
#   address3 - SOAP::SOAPString
#   countryCode - SOAP::SOAPString
#   county - SOAP::SOAPString
#   postalTown - SOAP::SOAPString
#   postcode - SOAP::SOAPString
class AddressWebModel
  attr_accessor :address1
  attr_accessor :address2
  attr_accessor :address3
  attr_accessor :countryCode
  attr_accessor :county
  attr_accessor :postalTown
  attr_accessor :postcode

  def initialize(address1 = nil, address2 = nil, address3 = nil, countryCode = nil, county = nil, postalTown = nil, postcode = nil)
    @address1 = address1
    @address2 = address2
    @address3 = address3
    @countryCode = countryCode
    @county = county
    @postalTown = postalTown
    @postcode = postcode
  end
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}UKMWebResponse
#   errors - UKMail::SoapService::Consignment::ArrayOfUKMWebError
#   result - UKMail::SoapService::Consignment::UKMResultState
#   warnings - UKMail::SoapService::Consignment::ArrayOfUKMWebWarning
class UKMWebResponse
  attr_accessor :errors
  attr_accessor :result
  attr_accessor :warnings

  def initialize(errors = nil, result = nil, warnings = nil)
    @errors = errors
    @result = result
    @warnings = warnings
  end
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}UKMAddDomesticConsignmentWebResponse
#   errors - UKMail::SoapService::Consignment::ArrayOfUKMWebError
#   result - UKMail::SoapService::Consignment::UKMResultState
#   warnings - UKMail::SoapService::Consignment::ArrayOfUKMWebWarning
#   consignmentNumber - SOAP::SOAPString
#   labels - UKMail::SoapService::Consignment::ArrayOfbase64Binary
class UKMAddDomesticConsignmentWebResponse < UKMWebResponse
  attr_accessor :errors
  attr_accessor :result
  attr_accessor :warnings
  attr_accessor :consignmentNumber
  attr_accessor :labels

  def initialize(errors = nil, result = nil, warnings = nil, consignmentNumber = nil, labels = nil)
    @errors = errors
    @result = result
    @warnings = warnings
    @consignmentNumber = consignmentNumber
    @labels = labels
  end
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}UKMAddInternationalConsignmentWebResponse
#   errors - UKMail::SoapService::Consignment::ArrayOfUKMWebError
#   result - UKMail::SoapService::Consignment::UKMResultState
#   warnings - UKMail::SoapService::Consignment::ArrayOfUKMWebWarning
#   consignmentNumber - SOAP::SOAPString
#   invoiceBytes - SOAP::SOAPBase64
#   labels - UKMail::SoapService::Consignment::ArrayOfbase64Binary
class UKMAddInternationalConsignmentWebResponse < UKMWebResponse
  attr_accessor :errors
  attr_accessor :result
  attr_accessor :warnings
  attr_accessor :consignmentNumber
  attr_accessor :invoiceBytes
  attr_accessor :labels

  def initialize(errors = nil, result = nil, warnings = nil, consignmentNumber = nil, invoiceBytes = nil, labels = nil)
    @errors = errors
    @result = result
    @warnings = warnings
    @consignmentNumber = consignmentNumber
    @invoiceBytes = invoiceBytes
    @labels = labels
  end
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}UKMAddReturnToSenderWebResponse
#   errors - UKMail::SoapService::Consignment::ArrayOfUKMWebError
#   result - UKMail::SoapService::Consignment::UKMResultState
#   warnings - UKMail::SoapService::Consignment::ArrayOfUKMWebWarning
#   consignmentNumber - SOAP::SOAPString
class UKMAddReturnToSenderWebResponse < UKMWebResponse
  attr_accessor :errors
  attr_accessor :result
  attr_accessor :warnings
  attr_accessor :consignmentNumber

  def initialize(errors = nil, result = nil, warnings = nil, consignmentNumber = nil)
    @errors = errors
    @result = result
    @warnings = warnings
    @consignmentNumber = consignmentNumber
  end
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}UKMAddSendToThirdPartyWebResponse
#   errors - UKMail::SoapService::Consignment::ArrayOfUKMWebError
#   result - UKMail::SoapService::Consignment::UKMResultState
#   warnings - UKMail::SoapService::Consignment::ArrayOfUKMWebWarning
#   consignmentNumber - SOAP::SOAPString
class UKMAddSendToThirdPartyWebResponse < UKMWebResponse
  attr_accessor :errors
  attr_accessor :result
  attr_accessor :warnings
  attr_accessor :consignmentNumber

  def initialize(errors = nil, result = nil, warnings = nil, consignmentNumber = nil)
    @errors = errors
    @result = result
    @warnings = warnings
    @consignmentNumber = consignmentNumber
  end
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}UKMCancelConsignmentWebResponse
#   errors - UKMail::SoapService::Consignment::ArrayOfUKMWebError
#   result - UKMail::SoapService::Consignment::UKMResultState
#   warnings - UKMail::SoapService::Consignment::ArrayOfUKMWebWarning
class UKMCancelConsignmentWebResponse < UKMWebResponse
  attr_accessor :errors
  attr_accessor :result
  attr_accessor :warnings

  def initialize(errors = nil, result = nil, warnings = nil)
    @errors = errors
    @result = result
    @warnings = warnings
  end
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}UKMCancelReturnWebResponse
#   errors - UKMail::SoapService::Consignment::ArrayOfUKMWebError
#   result - UKMail::SoapService::Consignment::UKMResultState
#   warnings - UKMail::SoapService::Consignment::ArrayOfUKMWebWarning
class UKMCancelReturnWebResponse < UKMWebResponse
  attr_accessor :errors
  attr_accessor :result
  attr_accessor :warnings

  def initialize(errors = nil, result = nil, warnings = nil)
    @errors = errors
    @result = result
    @warnings = warnings
  end
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}ServicePointWebModel
#   addressLine1 - SOAP::SOAPString
#   city - SOAP::SOAPString
#   code - SOAP::SOAPString
#   countryCode - SOAP::SOAPString
#   houseNo - SOAP::SOAPString
#   keyword - SOAP::SOAPString
#   postNumber - SOAP::SOAPString
#   postcode - SOAP::SOAPString
#   shopName - SOAP::SOAPString
class ServicePointWebModel
  attr_accessor :addressLine1
  attr_accessor :city
  attr_accessor :code
  attr_accessor :countryCode
  attr_accessor :houseNo
  attr_accessor :keyword
  attr_accessor :postNumber
  attr_accessor :postcode
  attr_accessor :shopName

  def initialize(addressLine1 = nil, city = nil, code = nil, countryCode = nil, houseNo = nil, keyword = nil, postNumber = nil, postcode = nil, shopName = nil)
    @addressLine1 = addressLine1
    @city = city
    @code = code
    @countryCode = countryCode
    @houseNo = houseNo
    @keyword = keyword
    @postNumber = postNumber
    @postcode = postcode
    @shopName = shopName
  end
end

# {http://schemas.datacontract.org/2004/07/UKMWebAPICommon.WebRequests}CustomsDeclaration
#   articles - UKMail::SoapService::Consignment::Articles
#   currencyCode - SOAP::SOAPString
#   invoiceDate - SOAP::SOAPDateTime
#   invoiceNumber - SOAP::SOAPString
#   invoiceType - UKMail::SoapService::Consignment::InvoiceType
#   reasonForExport - UKMail::SoapService::Consignment::ReasonForExport
#   shippingCharges - SOAP::SOAPDecimal
#   termsOfDelivery - UKMail::SoapService::Consignment::TermsOfDelivery
#   totalArticles - SOAP::SOAPInt
#   totalValue - SOAP::SOAPDecimal
class CustomsDeclaration
  attr_accessor :articles
  attr_accessor :currencyCode
  attr_accessor :invoiceDate
  attr_accessor :invoiceNumber
  attr_accessor :invoiceType
  attr_accessor :reasonForExport
  attr_accessor :shippingCharges
  attr_accessor :termsOfDelivery
  attr_accessor :totalArticles
  attr_accessor :totalValue

  def initialize(articles = nil, currencyCode = nil, invoiceDate = nil, invoiceNumber = nil, invoiceType = nil, reasonForExport = nil, shippingCharges = nil, termsOfDelivery = nil, totalArticles = nil, totalValue = nil)
    @articles = articles
    @currencyCode = currencyCode
    @invoiceDate = invoiceDate
    @invoiceNumber = invoiceNumber
    @invoiceType = invoiceType
    @reasonForExport = reasonForExport
    @shippingCharges = shippingCharges
    @termsOfDelivery = termsOfDelivery
    @totalArticles = totalArticles
    @totalValue = totalValue
  end
end

# {http://schemas.datacontract.org/2004/07/UKMWebAPICommon.WebRequests}Articles
#   article - UKMail::SoapService::Consignment::ArrayOfArticleDetail
class Articles
  attr_accessor :article

  def initialize(article = nil)
    @article = article
  end
end

# {http://schemas.datacontract.org/2004/07/UKMWebAPICommon.WebRequests}ArrayOfArticleDetail
class ArrayOfArticleDetail < ::Array
end

# {http://schemas.datacontract.org/2004/07/UKMWebAPICommon.WebRequests}ArticleDetail
#   commodityCode - SOAP::SOAPString
#   countryOfManufacture - SOAP::SOAPString
#   goodsDescription - SOAP::SOAPString
#   quantity - SOAP::SOAPInt
#   unitValue - SOAP::SOAPDouble
#   unitWeight - SOAP::SOAPDouble
class ArticleDetail
  attr_accessor :commodityCode
  attr_accessor :countryOfManufacture
  attr_accessor :goodsDescription
  attr_accessor :quantity
  attr_accessor :unitValue
  attr_accessor :unitWeight

  def initialize(commodityCode = nil, countryOfManufacture = nil, goodsDescription = nil, quantity = nil, unitValue = nil, unitWeight = nil)
    @commodityCode = commodityCode
    @countryOfManufacture = countryOfManufacture
    @goodsDescription = goodsDescription
    @quantity = quantity
    @unitValue = unitValue
    @unitWeight = unitWeight
  end
end

# {http://schemas.datacontract.org/2004/07/UKMWebAPICommon.WebRequests}Recipient
#   contactEmail - SOAP::SOAPString
#   contactName - SOAP::SOAPString
#   contactNumber - SOAP::SOAPString
#   recipientAddress - UKMail::SoapService::Consignment::RecipientAddress
#   taxReference - SOAP::SOAPString
class Recipient
  attr_accessor :contactEmail
  attr_accessor :contactName
  attr_accessor :contactNumber
  attr_accessor :recipientAddress
  attr_accessor :taxReference

  def initialize(contactEmail = nil, contactName = nil, contactNumber = nil, recipientAddress = nil, taxReference = nil)
    @contactEmail = contactEmail
    @contactName = contactName
    @contactNumber = contactNumber
    @recipientAddress = recipientAddress
    @taxReference = taxReference
  end
end

# {http://schemas.datacontract.org/2004/07/UKMWebAPICommon.WebRequests}RecipientAddress
#   address1 - SOAP::SOAPString
#   address2 - SOAP::SOAPString
#   address3 - SOAP::SOAPString
#   businessName - SOAP::SOAPString
#   countryCode - SOAP::SOAPString
#   county - SOAP::SOAPString
#   postalTown - SOAP::SOAPString
#   zipcode - SOAP::SOAPString
class RecipientAddress
  attr_accessor :address1
  attr_accessor :address2
  attr_accessor :address3
  attr_accessor :businessName
  attr_accessor :countryCode
  attr_accessor :county
  attr_accessor :postalTown
  attr_accessor :zipcode

  def initialize(address1 = nil, address2 = nil, address3 = nil, businessName = nil, countryCode = nil, county = nil, postalTown = nil, zipcode = nil)
    @address1 = address1
    @address2 = address2
    @address3 = address3
    @businessName = businessName
    @countryCode = countryCode
    @county = county
    @postalTown = postalTown
    @zipcode = zipcode
  end
end

# {http://schemas.microsoft.com/2003/10/Serialization/Arrays}ArrayOfbase64Binary
class ArrayOfbase64Binary < ::Array
end

# {http://schemas.microsoft.com/2003/10/Serialization/Arrays}ArrayOfstring
class ArrayOfstring < ::Array
end

# {http://schemas.datacontract.org/2004/07/iConsignCommon.Models}Model
#   entityIsDeleted - SOAP::SOAPBoolean
#   entityLastUpdated - SOAP::SOAPDateTime
#   entityRowId - SOAP::SOAPString
#   entityUpdatedBy - SOAP::SOAPString
class Model
  attr_accessor :entityIsDeleted
  attr_accessor :entityLastUpdated
  attr_accessor :entityRowId
  attr_accessor :entityUpdatedBy

  def initialize(entityIsDeleted = nil, entityLastUpdated = nil, entityRowId = nil, entityUpdatedBy = nil)
    @entityIsDeleted = entityIsDeleted
    @entityLastUpdated = entityLastUpdated
    @entityRowId = entityRowId
    @entityUpdatedBy = entityUpdatedBy
  end
end

# {http://schemas.datacontract.org/2004/07/iConsignCommon.Models}ProductAvailabilityModel
#   entityIsDeleted - SOAP::SOAPBoolean
#   entityLastUpdated - SOAP::SOAPDateTime
#   entityRowId - SOAP::SOAPString
#   entityUpdatedBy - SOAP::SOAPString
#   bulky - SOAP::SOAPBoolean
#   businessUnitCode - SOAP::SOAPInt
#   consignmentNumberType - SOAP::SOAPString
#   dhlProductCode - SOAP::SOAPInt
#   dhlProductId - SOAP::SOAPString
#   dhlProductName - SOAP::SOAPString
#   doorstep - SOAP::SOAPBoolean
#   fullCustomsDeclaration - SOAP::SOAPBoolean
#   iOSSRequired - SOAP::SOAPBoolean
#   internationalAirRoadType - SOAP::SOAPString
#   labelType - SOAP::SOAPString
#   maxItems - SOAP::SOAPInt
#   maxTransitTime - SOAP::SOAPInt
#   minTransitTime - SOAP::SOAPInt
#   productCode - SOAP::SOAPInt
#   productDescription - SOAP::SOAPString
#   productLabelDescription - SOAP::SOAPString
#   servicePointDelivery - SOAP::SOAPBoolean
#   servicePointTypes - UKMail::SoapService::Consignment::ArrayOfstring
#   sortOrder - SOAP::SOAPInt
#   transitTimeDescription - SOAP::SOAPString
class ProductAvailabilityModel < Model
  attr_accessor :entityIsDeleted
  attr_accessor :entityLastUpdated
  attr_accessor :entityRowId
  attr_accessor :entityUpdatedBy
  attr_accessor :bulky
  attr_accessor :businessUnitCode
  attr_accessor :consignmentNumberType
  attr_accessor :dhlProductCode
  attr_accessor :dhlProductId
  attr_accessor :dhlProductName
  attr_accessor :doorstep
  attr_accessor :fullCustomsDeclaration
  attr_accessor :iOSSRequired
  attr_accessor :internationalAirRoadType
  attr_accessor :labelType
  attr_accessor :maxItems
  attr_accessor :maxTransitTime
  attr_accessor :minTransitTime
  attr_accessor :productCode
  attr_accessor :productDescription
  attr_accessor :productLabelDescription
  attr_accessor :servicePointDelivery
  attr_accessor :servicePointTypes
  attr_accessor :sortOrder
  attr_accessor :transitTimeDescription

  def initialize(entityIsDeleted = nil, entityLastUpdated = nil, entityRowId = nil, entityUpdatedBy = nil, bulky = nil, businessUnitCode = nil, consignmentNumberType = nil, dhlProductCode = nil, dhlProductId = nil, dhlProductName = nil, doorstep = nil, fullCustomsDeclaration = nil, iOSSRequired = nil, internationalAirRoadType = nil, labelType = nil, maxItems = nil, maxTransitTime = nil, minTransitTime = nil, productCode = nil, productDescription = nil, productLabelDescription = nil, servicePointDelivery = nil, servicePointTypes = nil, sortOrder = nil, transitTimeDescription = nil)
    @entityIsDeleted = entityIsDeleted
    @entityLastUpdated = entityLastUpdated
    @entityRowId = entityRowId
    @entityUpdatedBy = entityUpdatedBy
    @bulky = bulky
    @businessUnitCode = businessUnitCode
    @consignmentNumberType = consignmentNumberType
    @dhlProductCode = dhlProductCode
    @dhlProductId = dhlProductId
    @dhlProductName = dhlProductName
    @doorstep = doorstep
    @fullCustomsDeclaration = fullCustomsDeclaration
    @iOSSRequired = iOSSRequired
    @internationalAirRoadType = internationalAirRoadType
    @labelType = labelType
    @maxItems = maxItems
    @maxTransitTime = maxTransitTime
    @minTransitTime = minTransitTime
    @productCode = productCode
    @productDescription = productDescription
    @productLabelDescription = productLabelDescription
    @servicePointDelivery = servicePointDelivery
    @servicePointTypes = servicePointTypes
    @sortOrder = sortOrder
    @transitTimeDescription = transitTimeDescription
  end
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}PreDeliveryNotificationType
class PreDeliveryNotificationType < ::String
  Email = new("Email")
  NonRequired = new("NonRequired")
  Telephone = new("Telephone")
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}InvoiceType
class InvoiceType < ::String
  Commercial = new("commercial")
  None = new("none")
  Proforma = new("proforma")
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}InvoiceTypeList
class InvoiceTypeList < ::String
  Commercial = new("Commercial")
  None = new("None")
  ProForma = new("ProForma")
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}LabelFormatType
class LabelFormatType < ::String
  PNG6x4 = new("PNG6x4")
  ZPL200dpi6x4 = new("ZPL200dpi6x4")
end

# {http://schemas.datacontract.org/2004/07/UKMWebAPICommon.WebRequests}ReasonForExport
class ReasonForExport < ::String
  CommercialSale = new("commercial sale")
  CommercialSample = new("commercial sample")
  Documents = new("documents")
  Gift = new("gift")
  Repairs = new("repairs")
  ReturnedGoods = new("returned goods")
end

# {http://schemas.datacontract.org/2004/07/UKMWebAPICommon.WebRequests}TermsOfDelivery
class TermsOfDelivery < ::String
  DAP = new("DAP")
  DDP = new("DDP")
end

# {http://schemas.datacontract.org/2004/07/UKMWebAPICommon.WebRequests}AddInternationalConsignmentWebRequest.DeliveryChoiceType
class AddInternationalConsignmentWebRequestDeliveryChoiceType < ::String
  DeliveryServicePoint = new("DeliveryServicePoint")
  RecipientAddress = new("RecipientAddress")
end

# {http://schemas.datacontract.org/2004/07/UKMWebAPICommon.WebResponses}UKMResultState
class UKMResultState < ::String
  Failed = new("Failed")
  Successful = new("Successful")
  Unknown = new("Unknown")
end

# {http://www.UKMail.com/Services/Contracts/ServiceContracts}AddDomesticConsignmentV2
#   request - UKMail::SoapService::Consignment::AddDomesticConsignmentWebRequestV2
class AddDomesticConsignmentV2
  attr_accessor :request

  def initialize(request = nil)
    @request = request
  end
end

# {http://www.UKMail.com/Services/Contracts/ServiceContracts}AddDomesticConsignmentV2Response
#   addDomesticConsignmentV2Result - UKMail::SoapService::Consignment::UKMAddDomesticConsignmentWebResponseV2
class AddDomesticConsignmentV2Response
  attr_accessor :addDomesticConsignmentV2Result

  def initialize(addDomesticConsignmentV2Result = nil)
    @addDomesticConsignmentV2Result = addDomesticConsignmentV2Result
  end
end

# {http://www.UKMail.com/Services/Contracts/ServiceContracts}CreateConsignmentV2
#   request - UKMail::SoapService::Consignment::AddDomesticConsignmentWebRequestV2
class CreateConsignmentV2
  attr_accessor :request

  def initialize(request = nil)
    @request = request
  end
end

# {http://www.UKMail.com/Services/Contracts/ServiceContracts}CreateConsignmentV2Response
#   createConsignmentV2Result - UKMail::SoapService::Consignment::UKMAddDomesticConsignmentWebResponseV2
class CreateConsignmentV2Response
  attr_accessor :createConsignmentV2Result

  def initialize(createConsignmentV2Result = nil)
    @createConsignmentV2Result = createConsignmentV2Result
  end
end

# {http://www.UKMail.com/Services/Contracts/ServiceContracts}CreateConsignmentV3
#   request - UKMail::SoapService::Consignment::AddDomesticConsignmentWebRequestV3
class CreateConsignmentV3
  attr_accessor :request

  def initialize(request = nil)
    @request = request
  end
end

# {http://www.UKMail.com/Services/Contracts/ServiceContracts}CreateConsignmentV3Response
#   createConsignmentV3Result - UKMail::SoapService::Consignment::UKMAddDomesticConsignmentWebResponseV2
class CreateConsignmentV3Response
  attr_accessor :createConsignmentV3Result

  def initialize(createConsignmentV3Result = nil)
    @createConsignmentV3Result = createConsignmentV3Result
  end
end

# {http://www.UKMail.com/Services/Contracts/ServiceContracts}GetLabelV2
#   request - UKMail::SoapService::Consignment::AddDomesticConsignmentWebRequestV2
#   response - UKMail::SoapService::Consignment::UKMAddDomesticConsignmentWebResponseV2
class GetLabelV2
  attr_accessor :request
  attr_accessor :response

  def initialize(request = nil, response = nil)
    @request = request
    @response = response
  end
end

# {http://www.UKMail.com/Services/Contracts/ServiceContracts}GetLabelV2Response
#   getLabelV2Result - UKMail::SoapService::Consignment::UKMAddDomesticConsignmentWebResponseV2
class GetLabelV2Response
  attr_accessor :getLabelV2Result

  def initialize(getLabelV2Result = nil)
    @getLabelV2Result = getLabelV2Result
  end
end

# {http://www.UKMail.com/Services/Contracts/ServiceContracts}AddDomesticConsignment
#   request - UKMail::SoapService::Consignment::AddDomesticConsignmentWebRequest
class AddDomesticConsignment
  attr_accessor :request

  def initialize(request = nil)
    @request = request
  end
end

# {http://www.UKMail.com/Services/Contracts/ServiceContracts}AddDomesticConsignmentResponse
#   addDomesticConsignmentResult - UKMail::SoapService::Consignment::UKMAddDomesticConsignmentWebResponse
class AddDomesticConsignmentResponse
  attr_accessor :addDomesticConsignmentResult

  def initialize(addDomesticConsignmentResult = nil)
    @addDomesticConsignmentResult = addDomesticConsignmentResult
  end
end

# {http://www.UKMail.com/Services/Contracts/ServiceContracts}AddInternationalConsignment
#   request - UKMail::SoapService::Consignment::AddInternationalConsignmentWebRequest
class AddInternationalConsignment
  attr_accessor :request

  def initialize(request = nil)
    @request = request
  end
end

# {http://www.UKMail.com/Services/Contracts/ServiceContracts}AddInternationalConsignmentResponse
#   addInternationalConsignmentResult - UKMail::SoapService::Consignment::UKMAddInternationalConsignmentWebResponse
class AddInternationalConsignmentResponse
  attr_accessor :addInternationalConsignmentResult

  def initialize(addInternationalConsignmentResult = nil)
    @addInternationalConsignmentResult = addInternationalConsignmentResult
  end
end

# {http://www.UKMail.com/Services/Contracts/ServiceContracts}AddInternationalConsignmentV2
#   request - UKMail::SoapService::Consignment::AddInternationalConsignmentWebRequestV2
class AddInternationalConsignmentV2
  attr_accessor :request

  def initialize(request = nil)
    @request = request
  end
end

# {http://www.UKMail.com/Services/Contracts/ServiceContracts}AddInternationalConsignmentV2Response
#   addInternationalConsignmentV2Result - UKMail::SoapService::Consignment::UKMAddInternationalConsignmentWebResponseV2
class AddInternationalConsignmentV2Response
  attr_accessor :addInternationalConsignmentV2Result

  def initialize(addInternationalConsignmentV2Result = nil)
    @addInternationalConsignmentV2Result = addInternationalConsignmentV2Result
  end
end

# {http://www.UKMail.com/Services/Contracts/ServiceContracts}AddReturnToSender
#   request - UKMail::SoapService::Consignment::AddReturnWebRequest
class AddReturnToSender
  attr_accessor :request

  def initialize(request = nil)
    @request = request
  end
end

# {http://www.UKMail.com/Services/Contracts/ServiceContracts}AddReturnToSenderResponse
#   addReturnToSenderResult - UKMail::SoapService::Consignment::UKMAddReturnToSenderWebResponse
class AddReturnToSenderResponse
  attr_accessor :addReturnToSenderResult

  def initialize(addReturnToSenderResult = nil)
    @addReturnToSenderResult = addReturnToSenderResult
  end
end

# {http://www.UKMail.com/Services/Contracts/ServiceContracts}AddSendToThirdParty
#   request - UKMail::SoapService::Consignment::AddSendToThirdPartyWebRequest
class AddSendToThirdParty
  attr_accessor :request

  def initialize(request = nil)
    @request = request
  end
end

# {http://www.UKMail.com/Services/Contracts/ServiceContracts}AddSendToThirdPartyResponse
#   addSendToThirdPartyResult - UKMail::SoapService::Consignment::UKMAddSendToThirdPartyWebResponse
class AddSendToThirdPartyResponse
  attr_accessor :addSendToThirdPartyResult

  def initialize(addSendToThirdPartyResult = nil)
    @addSendToThirdPartyResult = addSendToThirdPartyResult
  end
end

# {http://www.UKMail.com/Services/Contracts/ServiceContracts}CancelConsignment
#   request - UKMail::SoapService::Consignment::CancelConsignmentWebRequest
class CancelConsignment
  attr_accessor :request

  def initialize(request = nil)
    @request = request
  end
end

# {http://www.UKMail.com/Services/Contracts/ServiceContracts}CancelConsignmentResponse
#   cancelConsignmentResult - UKMail::SoapService::Consignment::UKMCancelConsignmentWebResponse
class CancelConsignmentResponse
  attr_accessor :cancelConsignmentResult

  def initialize(cancelConsignmentResult = nil)
    @cancelConsignmentResult = cancelConsignmentResult
  end
end

# {http://www.UKMail.com/Services/Contracts/ServiceContracts}CancelReturn
#   request - UKMail::SoapService::Consignment::CancelReturnWebRequest
class CancelReturn
  attr_accessor :request

  def initialize(request = nil)
    @request = request
  end
end

# {http://www.UKMail.com/Services/Contracts/ServiceContracts}CancelReturnResponse
#   cancelReturnResult - UKMail::SoapService::Consignment::UKMCancelReturnWebResponse
class CancelReturnResponse
  attr_accessor :cancelReturnResult

  def initialize(cancelReturnResult = nil)
    @cancelReturnResult = cancelReturnResult
  end
end

# {http://www.UKMail.com/Services/Contracts/ServiceContracts}AddDomesticConsignmentDeferred
#   request - UKMail::SoapService::Consignment::AddDomesticConsignmentDeferredWebRequest
class AddDomesticConsignmentDeferred
  attr_accessor :request

  def initialize(request = nil)
    @request = request
  end
end

# {http://www.UKMail.com/Services/Contracts/ServiceContracts}AddDomesticConsignmentDeferredResponse
#   addDomesticConsignmentDeferredResult - UKMail::SoapService::Consignment::UKMAddDomesticConsignmentWebResponse
class AddDomesticConsignmentDeferredResponse
  attr_accessor :addDomesticConsignmentDeferredResult

  def initialize(addDomesticConsignmentDeferredResult = nil)
    @addDomesticConsignmentDeferredResult = addDomesticConsignmentDeferredResult
  end
end

# {http://www.UKMail.com/Services/Contracts/ServiceContracts}AddDomesticConsignmentDeferredV2
#   request - UKMail::SoapService::Consignment::AddDomesticConsignmentDeferredWebRequestV2
class AddDomesticConsignmentDeferredV2
  attr_accessor :request

  def initialize(request = nil)
    @request = request
  end
end

# {http://www.UKMail.com/Services/Contracts/ServiceContracts}AddDomesticConsignmentDeferredV2Response
#   addDomesticConsignmentDeferredV2Result - UKMail::SoapService::Consignment::UKMAddDomesticConsignmentWebResponse
class AddDomesticConsignmentDeferredV2Response
  attr_accessor :addDomesticConsignmentDeferredV2Result

  def initialize(addDomesticConsignmentDeferredV2Result = nil)
    @addDomesticConsignmentDeferredV2Result = addDomesticConsignmentDeferredV2Result
  end
end

# {http://www.UKMail.com/Services/Contracts/ServiceContracts}AddInternationalConsignmentV3
#   request - UKMail::SoapService::Consignment::AddInternationalConsignmentWebRequestV3
class AddInternationalConsignmentV3
  attr_accessor :request

  def initialize(request = nil)
    @request = request
  end
end

# {http://www.UKMail.com/Services/Contracts/ServiceContracts}AddInternationalConsignmentV3Response
#   addInternationalConsignmentV3Result - UKMail::SoapService::Consignment::UKMAddInternationalConsignmentWebResponseV2
class AddInternationalConsignmentV3Response
  attr_accessor :addInternationalConsignmentV3Result

  def initialize(addInternationalConsignmentV3Result = nil)
    @addInternationalConsignmentV3Result = addInternationalConsignmentV3Result
  end
end

# {http://www.UKMail.com/Services/Contracts/ServiceContracts}GetShipmentProduct
#   webRequest - UKMail::SoapService::Consignment::AddInternationalConsignmentWebRequestV3
#   productcode - SOAP::SOAPInt
class GetShipmentProduct
  attr_accessor :webRequest
  attr_accessor :productcode

  def initialize(webRequest = nil, productcode = nil)
    @webRequest = webRequest
    @productcode = productcode
  end
end

# {http://www.UKMail.com/Services/Contracts/ServiceContracts}GetShipmentProductResponse
#   getShipmentProductResult - UKMail::SoapService::Consignment::ProductAvailabilityModel
class GetShipmentProductResponse
  attr_accessor :getShipmentProductResult

  def initialize(getShipmentProductResult = nil)
    @getShipmentProductResult = getShipmentProductResult
  end
end


end; end; end
