#!/usr/bin/env ruby
# encoding: UTF-8
# Generated by wsdl2ruby (SOAP4R-NG/2.0.6)
require_relative 'UKMConsignmentServiceDriver.rb'


module UKMail::SoapService::Consignment

endpoint_url = ARGV.shift
obj = IUKMConsignmentService.new(endpoint_url)

# run ruby with -d to see SOAP wiredumps.
obj.wiredump_dev = STDERR if $DEBUG

# SYNOPSIS
#   addDomesticConsignmentV2(parameters)
#
# ARGS
#   parameters      AddDomesticConsignmentV2 - {http://www.UKMail.com/Services/Contracts/ServiceContracts}AddDomesticConsignmentV2
#
# RETURNS
#   parameters      AddDomesticConsignmentV2Response - {http://www.UKMail.com/Services/Contracts/ServiceContracts}AddDomesticConsignmentV2Response
#
parameters = nil
puts obj.addDomesticConsignmentV2(parameters)

# SYNOPSIS
#   createConsignmentV2(parameters)
#
# ARGS
#   parameters      CreateConsignmentV2 - {http://www.UKMail.com/Services/Contracts/ServiceContracts}CreateConsignmentV2
#
# RETURNS
#   parameters      CreateConsignmentV2Response - {http://www.UKMail.com/Services/Contracts/ServiceContracts}CreateConsignmentV2Response
#
parameters = nil
puts obj.createConsignmentV2(parameters)

# SYNOPSIS
#   createConsignmentV3(parameters)
#
# ARGS
#   parameters      CreateConsignmentV3 - {http://www.UKMail.com/Services/Contracts/ServiceContracts}CreateConsignmentV3
#
# RETURNS
#   parameters      CreateConsignmentV3Response - {http://www.UKMail.com/Services/Contracts/ServiceContracts}CreateConsignmentV3Response
#
parameters = nil
puts obj.createConsignmentV3(parameters)

# SYNOPSIS
#   getLabelV2(parameters)
#
# ARGS
#   parameters      GetLabelV2 - {http://www.UKMail.com/Services/Contracts/ServiceContracts}GetLabelV2
#
# RETURNS
#   parameters      GetLabelV2Response - {http://www.UKMail.com/Services/Contracts/ServiceContracts}GetLabelV2Response
#
parameters = nil
puts obj.getLabelV2(parameters)

# SYNOPSIS
#   addDomesticConsignment(parameters)
#
# ARGS
#   parameters      AddDomesticConsignment - {http://www.UKMail.com/Services/Contracts/ServiceContracts}AddDomesticConsignment
#
# RETURNS
#   parameters      AddDomesticConsignmentResponse - {http://www.UKMail.com/Services/Contracts/ServiceContracts}AddDomesticConsignmentResponse
#
parameters = nil
puts obj.addDomesticConsignment(parameters)

# SYNOPSIS
#   addInternationalConsignment(parameters)
#
# ARGS
#   parameters      AddInternationalConsignment - {http://www.UKMail.com/Services/Contracts/ServiceContracts}AddInternationalConsignment
#
# RETURNS
#   parameters      AddInternationalConsignmentResponse - {http://www.UKMail.com/Services/Contracts/ServiceContracts}AddInternationalConsignmentResponse
#
parameters = nil
puts obj.addInternationalConsignment(parameters)

# SYNOPSIS
#   addInternationalConsignmentV2(parameters)
#
# ARGS
#   parameters      AddInternationalConsignmentV2 - {http://www.UKMail.com/Services/Contracts/ServiceContracts}AddInternationalConsignmentV2
#
# RETURNS
#   parameters      AddInternationalConsignmentV2Response - {http://www.UKMail.com/Services/Contracts/ServiceContracts}AddInternationalConsignmentV2Response
#
parameters = nil
puts obj.addInternationalConsignmentV2(parameters)

# SYNOPSIS
#   addReturnToSender(parameters)
#
# ARGS
#   parameters      AddReturnToSender - {http://www.UKMail.com/Services/Contracts/ServiceContracts}AddReturnToSender
#
# RETURNS
#   parameters      AddReturnToSenderResponse - {http://www.UKMail.com/Services/Contracts/ServiceContracts}AddReturnToSenderResponse
#
parameters = nil
puts obj.addReturnToSender(parameters)

# SYNOPSIS
#   addSendToThirdParty(parameters)
#
# ARGS
#   parameters      AddSendToThirdParty - {http://www.UKMail.com/Services/Contracts/ServiceContracts}AddSendToThirdParty
#
# RETURNS
#   parameters      AddSendToThirdPartyResponse - {http://www.UKMail.com/Services/Contracts/ServiceContracts}AddSendToThirdPartyResponse
#
parameters = nil
puts obj.addSendToThirdParty(parameters)

# SYNOPSIS
#   cancelConsignment(parameters)
#
# ARGS
#   parameters      CancelConsignment - {http://www.UKMail.com/Services/Contracts/ServiceContracts}CancelConsignment
#
# RETURNS
#   parameters      CancelConsignmentResponse - {http://www.UKMail.com/Services/Contracts/ServiceContracts}CancelConsignmentResponse
#
parameters = nil
puts obj.cancelConsignment(parameters)

# SYNOPSIS
#   cancelReturn(parameters)
#
# ARGS
#   parameters      CancelReturn - {http://www.UKMail.com/Services/Contracts/ServiceContracts}CancelReturn
#
# RETURNS
#   parameters      CancelReturnResponse - {http://www.UKMail.com/Services/Contracts/ServiceContracts}CancelReturnResponse
#
parameters = nil
puts obj.cancelReturn(parameters)

# SYNOPSIS
#   addDomesticConsignmentDeferred(parameters)
#
# ARGS
#   parameters      AddDomesticConsignmentDeferred - {http://www.UKMail.com/Services/Contracts/ServiceContracts}AddDomesticConsignmentDeferred
#
# RETURNS
#   parameters      AddDomesticConsignmentDeferredResponse - {http://www.UKMail.com/Services/Contracts/ServiceContracts}AddDomesticConsignmentDeferredResponse
#
parameters = nil
puts obj.addDomesticConsignmentDeferred(parameters)

# SYNOPSIS
#   addDomesticConsignmentDeferredV2(parameters)
#
# ARGS
#   parameters      AddDomesticConsignmentDeferredV2 - {http://www.UKMail.com/Services/Contracts/ServiceContracts}AddDomesticConsignmentDeferredV2
#
# RETURNS
#   parameters      AddDomesticConsignmentDeferredV2Response - {http://www.UKMail.com/Services/Contracts/ServiceContracts}AddDomesticConsignmentDeferredV2Response
#
parameters = nil
puts obj.addDomesticConsignmentDeferredV2(parameters)

# SYNOPSIS
#   addInternationalConsignmentV3(parameters)
#
# ARGS
#   parameters      AddInternationalConsignmentV3 - {http://www.UKMail.com/Services/Contracts/ServiceContracts}AddInternationalConsignmentV3
#
# RETURNS
#   parameters      AddInternationalConsignmentV3Response - {http://www.UKMail.com/Services/Contracts/ServiceContracts}AddInternationalConsignmentV3Response
#
parameters = nil
puts obj.addInternationalConsignmentV3(parameters)

# SYNOPSIS
#   getShipmentProduct(parameters)
#
# ARGS
#   parameters      GetShipmentProduct - {http://www.UKMail.com/Services/Contracts/ServiceContracts}GetShipmentProduct
#
# RETURNS
#   parameters      GetShipmentProductResponse - {http://www.UKMail.com/Services/Contracts/ServiceContracts}GetShipmentProductResponse
#
parameters = nil
puts obj.getShipmentProduct(parameters)




end
