# encoding: UTF-8
# Generated by wsdl2ruby (SOAP4R-NG/2.0.3)
require 'xsd/qname'

module UKMail; module SoapService; module Consignment


# {http://www.UKMail.com/Services/Contracts/DataContracts}WebRequest
#   authenticationToken - SOAP::SOAPString
#   username - SOAP::SOAPString
class WebRequest
  attr_accessor :authenticationToken
  attr_accessor :username

  def initialize(authenticationToken = nil, username = nil)
    @authenticationToken = authenticationToken
    @username = username
  end
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}AddConsignmentWebRequest
#   authenticationToken - SOAP::SOAPString
#   username - SOAP::SOAPString
#   accountNumber - SOAP::SOAPString
#   address - UKMail::SoapService::Consignment::AddressWebModel
#   alternativeRef - SOAP::SOAPString
#   businessName - SOAP::SOAPString
#   collectionJobNumber - SOAP::SOAPString
#   confirmationOfDelivery - SOAP::SOAPBoolean
#   contactName - SOAP::SOAPString
#   customersRef - SOAP::SOAPString
#   email - SOAP::SOAPString
#   items - SOAP::SOAPInt
#   serviceKey - SOAP::SOAPInt
#   specialInstructions1 - SOAP::SOAPString
#   specialInstructions2 - SOAP::SOAPString
#   telephone - SOAP::SOAPString
#   weight - SOAP::SOAPDecimal
class AddConsignmentWebRequest < WebRequest
  attr_accessor :authenticationToken
  attr_accessor :username
  attr_accessor :accountNumber
  attr_accessor :address
  attr_accessor :alternativeRef
  attr_accessor :businessName
  attr_accessor :collectionJobNumber
  attr_accessor :confirmationOfDelivery
  attr_accessor :contactName
  attr_accessor :customersRef
  attr_accessor :email
  attr_accessor :items
  attr_accessor :serviceKey
  attr_accessor :specialInstructions1
  attr_accessor :specialInstructions2
  attr_accessor :telephone
  attr_accessor :weight

  def initialize(authenticationToken = nil, username = nil, accountNumber = nil, address = nil, alternativeRef = nil, businessName = nil, collectionJobNumber = nil, confirmationOfDelivery = nil, contactName = nil, customersRef = nil, email = nil, items = nil, serviceKey = nil, specialInstructions1 = nil, specialInstructions2 = nil, telephone = nil, weight = nil)
    @authenticationToken = authenticationToken
    @username = username
    @accountNumber = accountNumber
    @address = address
    @alternativeRef = alternativeRef
    @businessName = businessName
    @collectionJobNumber = collectionJobNumber
    @confirmationOfDelivery = confirmationOfDelivery
    @contactName = contactName
    @customersRef = customersRef
    @email = email
    @items = items
    @serviceKey = serviceKey
    @specialInstructions1 = specialInstructions1
    @specialInstructions2 = specialInstructions2
    @telephone = telephone
    @weight = weight
  end
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}AddDomesticConsignmentWebRequest
#   authenticationToken - SOAP::SOAPString
#   username - SOAP::SOAPString
#   accountNumber - SOAP::SOAPString
#   address - UKMail::SoapService::Consignment::AddressWebModel
#   alternativeRef - SOAP::SOAPString
#   businessName - SOAP::SOAPString
#   collectionJobNumber - SOAP::SOAPString
#   confirmationOfDelivery - SOAP::SOAPBoolean
#   contactName - SOAP::SOAPString
#   customersRef - SOAP::SOAPString
#   email - SOAP::SOAPString
#   items - SOAP::SOAPInt
#   serviceKey - SOAP::SOAPInt
#   specialInstructions1 - SOAP::SOAPString
#   specialInstructions2 - SOAP::SOAPString
#   telephone - SOAP::SOAPString
#   weight - SOAP::SOAPDecimal
#   bookIn - SOAP::SOAPBoolean
#   cODAmount - SOAP::SOAPDecimal
#   confirmationEmail - SOAP::SOAPString
#   confirmationTelephone - SOAP::SOAPString
#   exchangeOnDelivery - SOAP::SOAPBoolean
#   extendedCover - SOAP::SOAPInt
#   longLength - SOAP::SOAPBoolean
#   preDeliveryNotification - UKMail::SoapService::Consignment::PreDeliveryNotificationType
#   secureLocation1 - SOAP::SOAPString
#   secureLocation2 - SOAP::SOAPString
#   signatureOptional - SOAP::SOAPBoolean
class AddDomesticConsignmentWebRequest < AddConsignmentWebRequest
  attr_accessor :authenticationToken
  attr_accessor :username
  attr_accessor :accountNumber
  attr_accessor :address
  attr_accessor :alternativeRef
  attr_accessor :businessName
  attr_accessor :collectionJobNumber
  attr_accessor :confirmationOfDelivery
  attr_accessor :contactName
  attr_accessor :customersRef
  attr_accessor :email
  attr_accessor :items
  attr_accessor :serviceKey
  attr_accessor :specialInstructions1
  attr_accessor :specialInstructions2
  attr_accessor :telephone
  attr_accessor :weight
  attr_accessor :bookIn
  attr_accessor :cODAmount
  attr_accessor :confirmationEmail
  attr_accessor :confirmationTelephone
  attr_accessor :exchangeOnDelivery
  attr_accessor :extendedCover
  attr_accessor :longLength
  attr_accessor :preDeliveryNotification
  attr_accessor :secureLocation1
  attr_accessor :secureLocation2
  attr_accessor :signatureOptional

  def initialize(authenticationToken = nil, username = nil, accountNumber = nil, address = nil, alternativeRef = nil, businessName = nil, collectionJobNumber = nil, confirmationOfDelivery = nil, contactName = nil, customersRef = nil, email = nil, items = nil, serviceKey = nil, specialInstructions1 = nil, specialInstructions2 = nil, telephone = nil, weight = nil, bookIn = nil, cODAmount = nil, confirmationEmail = nil, confirmationTelephone = nil, exchangeOnDelivery = nil, extendedCover = nil, longLength = nil, preDeliveryNotification = nil, secureLocation1 = nil, secureLocation2 = nil, signatureOptional = nil)
    @authenticationToken = authenticationToken
    @username = username
    @accountNumber = accountNumber
    @address = address
    @alternativeRef = alternativeRef
    @businessName = businessName
    @collectionJobNumber = collectionJobNumber
    @confirmationOfDelivery = confirmationOfDelivery
    @contactName = contactName
    @customersRef = customersRef
    @email = email
    @items = items
    @serviceKey = serviceKey
    @specialInstructions1 = specialInstructions1
    @specialInstructions2 = specialInstructions2
    @telephone = telephone
    @weight = weight
    @bookIn = bookIn
    @cODAmount = cODAmount
    @confirmationEmail = confirmationEmail
    @confirmationTelephone = confirmationTelephone
    @exchangeOnDelivery = exchangeOnDelivery
    @extendedCover = extendedCover
    @longLength = longLength
    @preDeliveryNotification = preDeliveryNotification
    @secureLocation1 = secureLocation1
    @secureLocation2 = secureLocation2
    @signatureOptional = signatureOptional
  end
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}AddInternationalConsignmentWebRequest
#   authenticationToken - SOAP::SOAPString
#   username - SOAP::SOAPString
#   accountNumber - SOAP::SOAPString
#   address - UKMail::SoapService::Consignment::AddressWebModel
#   alternativeRef - SOAP::SOAPString
#   businessName - SOAP::SOAPString
#   collectionJobNumber - SOAP::SOAPString
#   confirmationOfDelivery - SOAP::SOAPBoolean
#   contactName - SOAP::SOAPString
#   customersRef - SOAP::SOAPString
#   email - SOAP::SOAPString
#   items - SOAP::SOAPInt
#   serviceKey - SOAP::SOAPInt
#   specialInstructions1 - SOAP::SOAPString
#   specialInstructions2 - SOAP::SOAPString
#   telephone - SOAP::SOAPString
#   weight - SOAP::SOAPDecimal
#   currencyCode - SOAP::SOAPString
#   documentsOnly - SOAP::SOAPBoolean
#   extendedCoverRequired - SOAP::SOAPBoolean
#   goodsDescription1 - SOAP::SOAPString
#   goodsDescription2 - SOAP::SOAPString
#   goodsDescription3 - SOAP::SOAPString
#   height - SOAP::SOAPInt
#   inFreeCirculationEU - SOAP::SOAPBoolean
#   invoiceType - UKMail::SoapService::Consignment::InvoiceTypeList
#   length - SOAP::SOAPInt
#   noDangerousGoods - SOAP::SOAPBoolean
#   value - SOAP::SOAPDecimal
#   width - SOAP::SOAPInt
class AddInternationalConsignmentWebRequest < AddConsignmentWebRequest
  attr_accessor :authenticationToken
  attr_accessor :username
  attr_accessor :accountNumber
  attr_accessor :address
  attr_accessor :alternativeRef
  attr_accessor :businessName
  attr_accessor :collectionJobNumber
  attr_accessor :confirmationOfDelivery
  attr_accessor :contactName
  attr_accessor :customersRef
  attr_accessor :email
  attr_accessor :items
  attr_accessor :serviceKey
  attr_accessor :specialInstructions1
  attr_accessor :specialInstructions2
  attr_accessor :telephone
  attr_accessor :weight
  attr_accessor :currencyCode
  attr_accessor :documentsOnly
  attr_accessor :extendedCoverRequired
  attr_accessor :goodsDescription1
  attr_accessor :goodsDescription2
  attr_accessor :goodsDescription3
  attr_accessor :height
  attr_accessor :inFreeCirculationEU
  attr_accessor :invoiceType
  attr_accessor :length
  attr_accessor :noDangerousGoods
  attr_accessor :value
  attr_accessor :width

  def initialize(authenticationToken = nil, username = nil, accountNumber = nil, address = nil, alternativeRef = nil, businessName = nil, collectionJobNumber = nil, confirmationOfDelivery = nil, contactName = nil, customersRef = nil, email = nil, items = nil, serviceKey = nil, specialInstructions1 = nil, specialInstructions2 = nil, telephone = nil, weight = nil, currencyCode = nil, documentsOnly = nil, extendedCoverRequired = nil, goodsDescription1 = nil, goodsDescription2 = nil, goodsDescription3 = nil, height = nil, inFreeCirculationEU = nil, invoiceType = nil, length = nil, noDangerousGoods = nil, value = nil, width = nil)
    @authenticationToken = authenticationToken
    @username = username
    @accountNumber = accountNumber
    @address = address
    @alternativeRef = alternativeRef
    @businessName = businessName
    @collectionJobNumber = collectionJobNumber
    @confirmationOfDelivery = confirmationOfDelivery
    @contactName = contactName
    @customersRef = customersRef
    @email = email
    @items = items
    @serviceKey = serviceKey
    @specialInstructions1 = specialInstructions1
    @specialInstructions2 = specialInstructions2
    @telephone = telephone
    @weight = weight
    @currencyCode = currencyCode
    @documentsOnly = documentsOnly
    @extendedCoverRequired = extendedCoverRequired
    @goodsDescription1 = goodsDescription1
    @goodsDescription2 = goodsDescription2
    @goodsDescription3 = goodsDescription3
    @height = height
    @inFreeCirculationEU = inFreeCirculationEU
    @invoiceType = invoiceType
    @length = length
    @noDangerousGoods = noDangerousGoods
    @value = value
    @width = width
  end
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}AddPacketConsignmentWebRequest
#   authenticationToken - SOAP::SOAPString
#   username - SOAP::SOAPString
#   accountNumber - SOAP::SOAPString
#   collectionJobNumber - SOAP::SOAPString
#   contactName - SOAP::SOAPString
#   businessName - SOAP::SOAPString
#   address - UKMail::SoapService::Consignment::PacketAddressWebModel
#   customersRef - SOAP::SOAPString
#   alternativeRef - SOAP::SOAPString
#   weightInGrams - SOAP::SOAPInt
#   packetLength - SOAP::SOAPInt
#   packetWidth - SOAP::SOAPInt
#   packetHeight - SOAP::SOAPInt
#   deliveryMessage1 - SOAP::SOAPString
#   deliveryMessage2 - SOAP::SOAPString
class AddPacketConsignmentWebRequest < WebRequest
  attr_accessor :authenticationToken
  attr_accessor :username
  attr_accessor :accountNumber
  attr_accessor :collectionJobNumber
  attr_accessor :contactName
  attr_accessor :businessName
  attr_accessor :address
  attr_accessor :customersRef
  attr_accessor :alternativeRef
  attr_accessor :weightInGrams
  attr_accessor :packetLength
  attr_accessor :packetWidth
  attr_accessor :packetHeight
  attr_accessor :deliveryMessage1
  attr_accessor :deliveryMessage2

  def initialize(authenticationToken = nil, username = nil, accountNumber = nil, collectionJobNumber = nil, contactName = nil, businessName = nil, address = nil, customersRef = nil, alternativeRef = nil, weightInGrams = nil, packetLength = nil, packetWidth = nil, packetHeight = nil, deliveryMessage1 = nil, deliveryMessage2 = nil)
    @authenticationToken = authenticationToken
    @username = username
    @accountNumber = accountNumber
    @collectionJobNumber = collectionJobNumber
    @contactName = contactName
    @businessName = businessName
    @address = address
    @customersRef = customersRef
    @alternativeRef = alternativeRef
    @weightInGrams = weightInGrams
    @packetLength = packetLength
    @packetWidth = packetWidth
    @packetHeight = packetHeight
    @deliveryMessage1 = deliveryMessage1
    @deliveryMessage2 = deliveryMessage2
  end
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}AddReturnWebRequest
#   authenticationToken - SOAP::SOAPString
#   username - SOAP::SOAPString
#   accountNumber - SOAP::SOAPString
#   bookIn - SOAP::SOAPBoolean
#   collectionAddress - UKMail::SoapService::Consignment::AddressWebModel
#   collectionBusinessName - SOAP::SOAPString
#   collectionContactName - SOAP::SOAPString
#   collectionCustomersRef - SOAP::SOAPString
#   collectionDate - SOAP::SOAPDateTime
#   collectionEmail - SOAP::SOAPString
#   collectionLatestPickup - SOAP::SOAPDateTime
#   collectionOpenLunchtime - SOAP::SOAPBoolean
#   collectionSpecialInstructions1 - SOAP::SOAPString
#   collectionSpecialInstructions2 - SOAP::SOAPString
#   collectionTelephone - SOAP::SOAPString
#   collectionTimeReady - SOAP::SOAPDateTime
#   deliverySpecialInstructions1 - SOAP::SOAPString
#   deliverySpecialInstructions2 - SOAP::SOAPString
#   descriptionOfGoods1 - SOAP::SOAPString
#   descriptionOfGoods2 - SOAP::SOAPString
#   serviceKey - SOAP::SOAPInt
class AddReturnWebRequest < WebRequest
  attr_accessor :authenticationToken
  attr_accessor :username
  attr_accessor :accountNumber
  attr_accessor :bookIn
  attr_accessor :collectionAddress
  attr_accessor :collectionBusinessName
  attr_accessor :collectionContactName
  attr_accessor :collectionCustomersRef
  attr_accessor :collectionDate
  attr_accessor :collectionEmail
  attr_accessor :collectionLatestPickup
  attr_accessor :collectionOpenLunchtime
  attr_accessor :collectionSpecialInstructions1
  attr_accessor :collectionSpecialInstructions2
  attr_accessor :collectionTelephone
  attr_accessor :collectionTimeReady
  attr_accessor :deliverySpecialInstructions1
  attr_accessor :deliverySpecialInstructions2
  attr_accessor :descriptionOfGoods1
  attr_accessor :descriptionOfGoods2
  attr_accessor :serviceKey

  def initialize(authenticationToken = nil, username = nil, accountNumber = nil, bookIn = nil, collectionAddress = nil, collectionBusinessName = nil, collectionContactName = nil, collectionCustomersRef = nil, collectionDate = nil, collectionEmail = nil, collectionLatestPickup = nil, collectionOpenLunchtime = nil, collectionSpecialInstructions1 = nil, collectionSpecialInstructions2 = nil, collectionTelephone = nil, collectionTimeReady = nil, deliverySpecialInstructions1 = nil, deliverySpecialInstructions2 = nil, descriptionOfGoods1 = nil, descriptionOfGoods2 = nil, serviceKey = nil)
    @authenticationToken = authenticationToken
    @username = username
    @accountNumber = accountNumber
    @bookIn = bookIn
    @collectionAddress = collectionAddress
    @collectionBusinessName = collectionBusinessName
    @collectionContactName = collectionContactName
    @collectionCustomersRef = collectionCustomersRef
    @collectionDate = collectionDate
    @collectionEmail = collectionEmail
    @collectionLatestPickup = collectionLatestPickup
    @collectionOpenLunchtime = collectionOpenLunchtime
    @collectionSpecialInstructions1 = collectionSpecialInstructions1
    @collectionSpecialInstructions2 = collectionSpecialInstructions2
    @collectionTelephone = collectionTelephone
    @collectionTimeReady = collectionTimeReady
    @deliverySpecialInstructions1 = deliverySpecialInstructions1
    @deliverySpecialInstructions2 = deliverySpecialInstructions2
    @descriptionOfGoods1 = descriptionOfGoods1
    @descriptionOfGoods2 = descriptionOfGoods2
    @serviceKey = serviceKey
  end
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}AddSendToThirdPartyWebRequest
#   authenticationToken - SOAP::SOAPString
#   username - SOAP::SOAPString
#   accountNumber - SOAP::SOAPString
#   bookIn - SOAP::SOAPBoolean
#   collectionAddress - UKMail::SoapService::Consignment::AddressWebModel
#   collectionBusinessName - SOAP::SOAPString
#   collectionContactName - SOAP::SOAPString
#   collectionCustomersRef - SOAP::SOAPString
#   collectionDate - SOAP::SOAPDateTime
#   collectionEmail - SOAP::SOAPString
#   collectionLatestPickup - SOAP::SOAPDateTime
#   collectionOpenLunchtime - SOAP::SOAPBoolean
#   collectionSpecialInstructions1 - SOAP::SOAPString
#   collectionSpecialInstructions2 - SOAP::SOAPString
#   collectionTelephone - SOAP::SOAPString
#   collectionTimeReady - SOAP::SOAPDateTime
#   deliverySpecialInstructions1 - SOAP::SOAPString
#   deliverySpecialInstructions2 - SOAP::SOAPString
#   descriptionOfGoods1 - SOAP::SOAPString
#   descriptionOfGoods2 - SOAP::SOAPString
#   serviceKey - SOAP::SOAPInt
#   deliveryAddress - UKMail::SoapService::Consignment::AddressWebModel
#   deliveryBusinessName - SOAP::SOAPString
#   deliveryContactName - SOAP::SOAPString
#   deliveryEmail - SOAP::SOAPString
#   deliveryTelephone - SOAP::SOAPString
class AddSendToThirdPartyWebRequest < AddReturnWebRequest
  attr_accessor :authenticationToken
  attr_accessor :username
  attr_accessor :accountNumber
  attr_accessor :bookIn
  attr_accessor :collectionAddress
  attr_accessor :collectionBusinessName
  attr_accessor :collectionContactName
  attr_accessor :collectionCustomersRef
  attr_accessor :collectionDate
  attr_accessor :collectionEmail
  attr_accessor :collectionLatestPickup
  attr_accessor :collectionOpenLunchtime
  attr_accessor :collectionSpecialInstructions1
  attr_accessor :collectionSpecialInstructions2
  attr_accessor :collectionTelephone
  attr_accessor :collectionTimeReady
  attr_accessor :deliverySpecialInstructions1
  attr_accessor :deliverySpecialInstructions2
  attr_accessor :descriptionOfGoods1
  attr_accessor :descriptionOfGoods2
  attr_accessor :serviceKey
  attr_accessor :deliveryAddress
  attr_accessor :deliveryBusinessName
  attr_accessor :deliveryContactName
  attr_accessor :deliveryEmail
  attr_accessor :deliveryTelephone

  def initialize(authenticationToken = nil, username = nil, accountNumber = nil, bookIn = nil, collectionAddress = nil, collectionBusinessName = nil, collectionContactName = nil, collectionCustomersRef = nil, collectionDate = nil, collectionEmail = nil, collectionLatestPickup = nil, collectionOpenLunchtime = nil, collectionSpecialInstructions1 = nil, collectionSpecialInstructions2 = nil, collectionTelephone = nil, collectionTimeReady = nil, deliverySpecialInstructions1 = nil, deliverySpecialInstructions2 = nil, descriptionOfGoods1 = nil, descriptionOfGoods2 = nil, serviceKey = nil, deliveryAddress = nil, deliveryBusinessName = nil, deliveryContactName = nil, deliveryEmail = nil, deliveryTelephone = nil)
    @authenticationToken = authenticationToken
    @username = username
    @accountNumber = accountNumber
    @bookIn = bookIn
    @collectionAddress = collectionAddress
    @collectionBusinessName = collectionBusinessName
    @collectionContactName = collectionContactName
    @collectionCustomersRef = collectionCustomersRef
    @collectionDate = collectionDate
    @collectionEmail = collectionEmail
    @collectionLatestPickup = collectionLatestPickup
    @collectionOpenLunchtime = collectionOpenLunchtime
    @collectionSpecialInstructions1 = collectionSpecialInstructions1
    @collectionSpecialInstructions2 = collectionSpecialInstructions2
    @collectionTelephone = collectionTelephone
    @collectionTimeReady = collectionTimeReady
    @deliverySpecialInstructions1 = deliverySpecialInstructions1
    @deliverySpecialInstructions2 = deliverySpecialInstructions2
    @descriptionOfGoods1 = descriptionOfGoods1
    @descriptionOfGoods2 = descriptionOfGoods2
    @serviceKey = serviceKey
    @deliveryAddress = deliveryAddress
    @deliveryBusinessName = deliveryBusinessName
    @deliveryContactName = deliveryContactName
    @deliveryEmail = deliveryEmail
    @deliveryTelephone = deliveryTelephone
  end
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}CancelConsignmentWebRequest
#   authenticationToken - SOAP::SOAPString
#   username - SOAP::SOAPString
#   consignmentNumber - SOAP::SOAPString
class CancelConsignmentWebRequest < WebRequest
  attr_accessor :authenticationToken
  attr_accessor :username
  attr_accessor :consignmentNumber

  def initialize(authenticationToken = nil, username = nil, consignmentNumber = nil)
    @authenticationToken = authenticationToken
    @username = username
    @consignmentNumber = consignmentNumber
  end
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}CancelReturnWebRequest
#   authenticationToken - SOAP::SOAPString
#   username - SOAP::SOAPString
#   consignmentNumber - SOAP::SOAPString
class CancelReturnWebRequest < WebRequest
  attr_accessor :authenticationToken
  attr_accessor :username
  attr_accessor :consignmentNumber

  def initialize(authenticationToken = nil, username = nil, consignmentNumber = nil)
    @authenticationToken = authenticationToken
    @username = username
    @consignmentNumber = consignmentNumber
  end
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}AddConsignmentDeferredWebRequest
#   authenticationToken - SOAP::SOAPString
#   username - SOAP::SOAPString
#   accountNumber - SOAP::SOAPString
#   address - UKMail::SoapService::Consignment::AddressWebModel
#   alternativeRef - SOAP::SOAPString
#   businessName - SOAP::SOAPString
#   collectionDate - SOAP::SOAPDateTime
#   confirmationOfDelivery - SOAP::SOAPBoolean
#   contactName - SOAP::SOAPString
#   customersRef - SOAP::SOAPString
#   email - SOAP::SOAPString
#   items - SOAP::SOAPInt
#   labelFormat - UKMail::SoapService::Consignment::LabelFormatType
#   serviceKey - SOAP::SOAPInt
#   specialInstructions1 - SOAP::SOAPString
#   specialInstructions2 - SOAP::SOAPString
#   telephone - SOAP::SOAPString
#   weight - SOAP::SOAPDecimal
class AddConsignmentDeferredWebRequest < WebRequest
  attr_accessor :authenticationToken
  attr_accessor :username
  attr_accessor :accountNumber
  attr_accessor :address
  attr_accessor :alternativeRef
  attr_accessor :businessName
  attr_accessor :collectionDate
  attr_accessor :confirmationOfDelivery
  attr_accessor :contactName
  attr_accessor :customersRef
  attr_accessor :email
  attr_accessor :items
  attr_accessor :labelFormat
  attr_accessor :serviceKey
  attr_accessor :specialInstructions1
  attr_accessor :specialInstructions2
  attr_accessor :telephone
  attr_accessor :weight

  def initialize(authenticationToken = nil, username = nil, accountNumber = nil, address = nil, alternativeRef = nil, businessName = nil, collectionDate = nil, confirmationOfDelivery = nil, contactName = nil, customersRef = nil, email = nil, items = nil, labelFormat = nil, serviceKey = nil, specialInstructions1 = nil, specialInstructions2 = nil, telephone = nil, weight = nil)
    @authenticationToken = authenticationToken
    @username = username
    @accountNumber = accountNumber
    @address = address
    @alternativeRef = alternativeRef
    @businessName = businessName
    @collectionDate = collectionDate
    @confirmationOfDelivery = confirmationOfDelivery
    @contactName = contactName
    @customersRef = customersRef
    @email = email
    @items = items
    @labelFormat = labelFormat
    @serviceKey = serviceKey
    @specialInstructions1 = specialInstructions1
    @specialInstructions2 = specialInstructions2
    @telephone = telephone
    @weight = weight
  end
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}AddDomesticConsignmentDeferredWebRequest
#   authenticationToken - SOAP::SOAPString
#   username - SOAP::SOAPString
#   accountNumber - SOAP::SOAPString
#   address - UKMail::SoapService::Consignment::AddressWebModel
#   alternativeRef - SOAP::SOAPString
#   businessName - SOAP::SOAPString
#   collectionDate - SOAP::SOAPDateTime
#   confirmationOfDelivery - SOAP::SOAPBoolean
#   contactName - SOAP::SOAPString
#   customersRef - SOAP::SOAPString
#   email - SOAP::SOAPString
#   items - SOAP::SOAPInt
#   labelFormat - UKMail::SoapService::Consignment::LabelFormatType
#   serviceKey - SOAP::SOAPInt
#   specialInstructions1 - SOAP::SOAPString
#   specialInstructions2 - SOAP::SOAPString
#   telephone - SOAP::SOAPString
#   weight - SOAP::SOAPDecimal
#   bookIn - SOAP::SOAPBoolean
#   cODAmount - SOAP::SOAPDecimal
#   confirmationEmail - SOAP::SOAPString
#   confirmationTelephone - SOAP::SOAPString
#   exchangeOnDelivery - SOAP::SOAPBoolean
#   extendedCover - SOAP::SOAPInt
#   longLength - SOAP::SOAPBoolean
#   preDeliveryNotification - UKMail::SoapService::Consignment::PreDeliveryNotificationType
#   secureLocation1 - SOAP::SOAPString
#   secureLocation2 - SOAP::SOAPString
#   signatureOptional - SOAP::SOAPBoolean
class AddDomesticConsignmentDeferredWebRequest < AddConsignmentDeferredWebRequest
  attr_accessor :authenticationToken
  attr_accessor :username
  attr_accessor :accountNumber
  attr_accessor :address
  attr_accessor :alternativeRef
  attr_accessor :businessName
  attr_accessor :collectionDate
  attr_accessor :confirmationOfDelivery
  attr_accessor :contactName
  attr_accessor :customersRef
  attr_accessor :email
  attr_accessor :items
  attr_accessor :labelFormat
  attr_accessor :serviceKey
  attr_accessor :specialInstructions1
  attr_accessor :specialInstructions2
  attr_accessor :telephone
  attr_accessor :weight
  attr_accessor :bookIn
  attr_accessor :cODAmount
  attr_accessor :confirmationEmail
  attr_accessor :confirmationTelephone
  attr_accessor :exchangeOnDelivery
  attr_accessor :extendedCover
  attr_accessor :longLength
  attr_accessor :preDeliveryNotification
  attr_accessor :secureLocation1
  attr_accessor :secureLocation2
  attr_accessor :signatureOptional

  def initialize(authenticationToken = nil, username = nil, accountNumber = nil, address = nil, alternativeRef = nil, businessName = nil, collectionDate = nil, confirmationOfDelivery = nil, contactName = nil, customersRef = nil, email = nil, items = nil, labelFormat = nil, serviceKey = nil, specialInstructions1 = nil, specialInstructions2 = nil, telephone = nil, weight = nil, bookIn = nil, cODAmount = nil, confirmationEmail = nil, confirmationTelephone = nil, exchangeOnDelivery = nil, extendedCover = nil, longLength = nil, preDeliveryNotification = nil, secureLocation1 = nil, secureLocation2 = nil, signatureOptional = nil)
    @authenticationToken = authenticationToken
    @username = username
    @accountNumber = accountNumber
    @address = address
    @alternativeRef = alternativeRef
    @businessName = businessName
    @collectionDate = collectionDate
    @confirmationOfDelivery = confirmationOfDelivery
    @contactName = contactName
    @customersRef = customersRef
    @email = email
    @items = items
    @labelFormat = labelFormat
    @serviceKey = serviceKey
    @specialInstructions1 = specialInstructions1
    @specialInstructions2 = specialInstructions2
    @telephone = telephone
    @weight = weight
    @bookIn = bookIn
    @cODAmount = cODAmount
    @confirmationEmail = confirmationEmail
    @confirmationTelephone = confirmationTelephone
    @exchangeOnDelivery = exchangeOnDelivery
    @extendedCover = extendedCover
    @longLength = longLength
    @preDeliveryNotification = preDeliveryNotification
    @secureLocation1 = secureLocation1
    @secureLocation2 = secureLocation2
    @signatureOptional = signatureOptional
  end
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}AddressWebModel
#   address1 - SOAP::SOAPString
#   address2 - SOAP::SOAPString
#   address3 - SOAP::SOAPString
#   countryCode - SOAP::SOAPString
#   county - SOAP::SOAPString
#   postalTown - SOAP::SOAPString
#   postcode - SOAP::SOAPString
class AddressWebModel
  attr_accessor :address1
  attr_accessor :address2
  attr_accessor :address3
  attr_accessor :countryCode
  attr_accessor :county
  attr_accessor :postalTown
  attr_accessor :postcode

  def initialize(address1 = nil, address2 = nil, address3 = nil, countryCode = nil, county = nil, postalTown = nil, postcode = nil)
    @address1 = address1
    @address2 = address2
    @address3 = address3
    @countryCode = countryCode
    @county = county
    @postalTown = postalTown
    @postcode = postcode
  end
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}UKMWebResponse
#   errors - UKMail::SoapService::Consignment::ArrayOfUKMWebError
#   result - UKMail::SoapService::Consignment::UKMResultState
#   warnings - UKMail::SoapService::Consignment::ArrayOfUKMWebWarning
class UKMWebResponse
  attr_accessor :errors
  attr_accessor :result
  attr_accessor :warnings

  def initialize(errors = nil, result = nil, warnings = nil)
    @errors = errors
    @result = result
    @warnings = warnings
  end
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}UKMAddDomesticConsignmentWebResponse
#   errors - UKMail::SoapService::Consignment::ArrayOfUKMWebError
#   result - UKMail::SoapService::Consignment::UKMResultState
#   warnings - UKMail::SoapService::Consignment::ArrayOfUKMWebWarning
#   consignmentNumber - SOAP::SOAPString
#   labels - UKMail::SoapService::Consignment::ArrayOfbase64Binary
class UKMAddDomesticConsignmentWebResponse < UKMWebResponse
  attr_accessor :errors
  attr_accessor :result
  attr_accessor :warnings
  attr_accessor :consignmentNumber
  attr_accessor :labels

  def initialize(errors = nil, result = nil, warnings = nil, consignmentNumber = nil, labels = nil)
    @errors = errors
    @result = result
    @warnings = warnings
    @consignmentNumber = consignmentNumber
    @labels = labels
  end
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}UKMAddPacketConsignmentWebResponse
#   errors - UKMail::SoapService::Consignment::ArrayOfUKMWebError
#   result - UKMail::SoapService::Consignment::UKMResultState
#   warnings - UKMail::SoapService::Consignment::ArrayOfUKMWebWarning
#   consignmentNumber - SOAP::SOAPString
#   labels - UKMail::SoapService::Consignment::ArrayOfbase64Binary
class UKMAddPacketConsignmentWebResponse < UKMWebResponse
  attr_accessor :errors
  attr_accessor :result
  attr_accessor :warnings
  attr_accessor :consignmentNumber
  attr_accessor :labels

  def initialize(errors = nil, result = nil, warnings = nil, consignmentNumber = nil, labels = nil)
    @errors = errors
    @result = result
    @warnings = warnings
    @consignmentNumber = consignmentNumber
    @labels = labels
  end
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}UKMAddInternationalConsignmentWebResponse
#   errors - UKMail::SoapService::Consignment::ArrayOfUKMWebError
#   result - UKMail::SoapService::Consignment::UKMResultState
#   warnings - UKMail::SoapService::Consignment::ArrayOfUKMWebWarning
#   consignmentNumber - SOAP::SOAPString
#   invoiceBytes - SOAP::SOAPBase64
#   labels - UKMail::SoapService::Consignment::ArrayOfbase64Binary
class UKMAddInternationalConsignmentWebResponse < UKMWebResponse
  attr_accessor :errors
  attr_accessor :result
  attr_accessor :warnings
  attr_accessor :consignmentNumber
  attr_accessor :invoiceBytes
  attr_accessor :labels

  def initialize(errors = nil, result = nil, warnings = nil, consignmentNumber = nil, invoiceBytes = nil, labels = nil)
    @errors = errors
    @result = result
    @warnings = warnings
    @consignmentNumber = consignmentNumber
    @invoiceBytes = invoiceBytes
    @labels = labels
  end
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}UKMAddReturnToSenderWebResponse
#   errors - UKMail::SoapService::Consignment::ArrayOfUKMWebError
#   result - UKMail::SoapService::Consignment::UKMResultState
#   warnings - UKMail::SoapService::Consignment::ArrayOfUKMWebWarning
#   consignmentNumber - SOAP::SOAPString
class UKMAddReturnToSenderWebResponse < UKMWebResponse
  attr_accessor :errors
  attr_accessor :result
  attr_accessor :warnings
  attr_accessor :consignmentNumber

  def initialize(errors = nil, result = nil, warnings = nil, consignmentNumber = nil)
    @errors = errors
    @result = result
    @warnings = warnings
    @consignmentNumber = consignmentNumber
  end
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}UKMAddSendToThirdPartyWebResponse
#   errors - UKMail::SoapService::Consignment::ArrayOfUKMWebError
#   result - UKMail::SoapService::Consignment::UKMResultState
#   warnings - UKMail::SoapService::Consignment::ArrayOfUKMWebWarning
#   consignmentNumber - SOAP::SOAPString
class UKMAddSendToThirdPartyWebResponse < UKMWebResponse
  attr_accessor :errors
  attr_accessor :result
  attr_accessor :warnings
  attr_accessor :consignmentNumber

  def initialize(errors = nil, result = nil, warnings = nil, consignmentNumber = nil)
    @errors = errors
    @result = result
    @warnings = warnings
    @consignmentNumber = consignmentNumber
  end
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}UKMCancelConsignmentWebResponse
#   errors - UKMail::SoapService::Consignment::ArrayOfUKMWebError
#   result - UKMail::SoapService::Consignment::UKMResultState
#   warnings - UKMail::SoapService::Consignment::ArrayOfUKMWebWarning
class UKMCancelConsignmentWebResponse < UKMWebResponse
  attr_accessor :errors
  attr_accessor :result
  attr_accessor :warnings

  def initialize(errors = nil, result = nil, warnings = nil)
    @errors = errors
    @result = result
    @warnings = warnings
  end
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}UKMCancelReturnWebResponse
#   errors - UKMail::SoapService::Consignment::ArrayOfUKMWebError
#   result - UKMail::SoapService::Consignment::UKMResultState
#   warnings - UKMail::SoapService::Consignment::ArrayOfUKMWebWarning
class UKMCancelReturnWebResponse < UKMWebResponse
  attr_accessor :errors
  attr_accessor :result
  attr_accessor :warnings

  def initialize(errors = nil, result = nil, warnings = nil)
    @errors = errors
    @result = result
    @warnings = warnings
  end
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}ArrayOfUKMWebError
class ArrayOfUKMWebError < ::Array
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}UKMWebError
#   code - SOAP::SOAPInt
#   description - SOAP::SOAPString
class UKMWebError
  attr_accessor :code
  attr_accessor :description

  def initialize(code = nil, description = nil)
    @code = code
    @description = description
  end
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}ArrayOfUKMWebWarning
class ArrayOfUKMWebWarning < ::Array
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}UKMWebWarning
#   code - SOAP::SOAPInt
#   description - SOAP::SOAPString
class UKMWebWarning
  attr_accessor :code
  attr_accessor :description

  def initialize(code = nil, description = nil)
    @code = code
    @description = description
  end
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}PacketAddressWebModel
#   address1 - SOAP::SOAPString
#   address2 - SOAP::SOAPString
#   address3 - SOAP::SOAPString
#   county - SOAP::SOAPString
#   postalTown - SOAP::SOAPString
#   postcode - SOAP::SOAPString
class PacketAddressWebModel
  attr_accessor :address1
  attr_accessor :address2
  attr_accessor :address3
  attr_accessor :county
  attr_accessor :postalTown
  attr_accessor :postcode

  def initialize(address1 = nil, address2 = nil, address3 = nil, county = nil, postalTown = nil, postcode = nil)
    @address1 = address1
    @address2 = address2
    @address3 = address3
    @county = county
    @postalTown = postalTown
    @postcode = postcode
  end
end

# {http://schemas.microsoft.com/2003/10/Serialization/Arrays}ArrayOfbase64Binary
class ArrayOfbase64Binary < ::Array
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}PreDeliveryNotificationType
class PreDeliveryNotificationType < ::String
  Email = new("Email")
  NonRequired = new("NonRequired")
  Telephone = new("Telephone")
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}InvoiceTypeList
class InvoiceTypeList < ::String
  Commercial = new("Commercial")
  None = new("None")
  ProForma = new("ProForma")
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}LabelFormatType
class LabelFormatType < ::String
  PNG6x4 = new("PNG6x4")
  ZPL200dpi6x4 = new("ZPL200dpi6x4")
end

# {http://schemas.datacontract.org/2004/07/UKMWebAPICommon.WebResponses}UKMResultState
class UKMResultState < ::String
  Failed = new("Failed")
  Successful = new("Successful")
  Unknown = new("Unknown")
end

# {http://www.UKMail.com/Services/Contracts/ServiceContracts}AddDomesticConsignment
#   request - UKMail::SoapService::Consignment::AddDomesticConsignmentWebRequest
class AddDomesticConsignment
  attr_accessor :request

  def initialize(request = nil)
    @request = request
  end
end

# {http://www.UKMail.com/Services/Contracts/ServiceContracts}AddDomesticConsignmentResponse
#   addDomesticConsignmentResult - UKMail::SoapService::Consignment::UKMAddDomesticConsignmentWebResponse
class AddDomesticConsignmentResponse
  attr_accessor :addDomesticConsignmentResult

  def initialize(addDomesticConsignmentResult = nil)
    @addDomesticConsignmentResult = addDomesticConsignmentResult
  end
end

# {http://www.UKMail.com/Services/Contracts/ServiceContracts}AddPacketConsignment
#   request - UKMail::SoapService::Consignment::AddPacketConsignmentWebRequest
class AddPacketConsignment
  attr_accessor :request

  def initialize(request = nil)
    @request = request
  end
end

# {http://www.UKMail.com/Services/Contracts/ServiceContracts}AddPacketConsignmentResponse
#   addPacketConsignmentResult - UKMail::SoapService::Consignment::UKMAddPacketConsignmentWebResponse
class AddPacketConsignmentResponse
  attr_accessor :addPacketConsignmentResult

  def initialize(addPacketConsignmentResult = nil)
    @addPacketConsignmentResult = addPacketConsignmentResult
  end
end

# {http://www.UKMail.com/Services/Contracts/ServiceContracts}AddInternationalConsignment
#   request - UKMail::SoapService::Consignment::AddInternationalConsignmentWebRequest
class AddInternationalConsignment
  attr_accessor :request

  def initialize(request = nil)
    @request = request
  end
end

# {http://www.UKMail.com/Services/Contracts/ServiceContracts}AddInternationalConsignmentResponse
#   addInternationalConsignmentResult - UKMail::SoapService::Consignment::UKMAddInternationalConsignmentWebResponse
class AddInternationalConsignmentResponse
  attr_accessor :addInternationalConsignmentResult

  def initialize(addInternationalConsignmentResult = nil)
    @addInternationalConsignmentResult = addInternationalConsignmentResult
  end
end

# {http://www.UKMail.com/Services/Contracts/ServiceContracts}AddReturnToSender
#   request - UKMail::SoapService::Consignment::AddReturnWebRequest
class AddReturnToSender
  attr_accessor :request

  def initialize(request = nil)
    @request = request
  end
end

# {http://www.UKMail.com/Services/Contracts/ServiceContracts}AddReturnToSenderResponse
#   addReturnToSenderResult - UKMail::SoapService::Consignment::UKMAddReturnToSenderWebResponse
class AddReturnToSenderResponse
  attr_accessor :addReturnToSenderResult

  def initialize(addReturnToSenderResult = nil)
    @addReturnToSenderResult = addReturnToSenderResult
  end
end

# {http://www.UKMail.com/Services/Contracts/ServiceContracts}AddSendToThirdParty
#   request - UKMail::SoapService::Consignment::AddSendToThirdPartyWebRequest
class AddSendToThirdParty
  attr_accessor :request

  def initialize(request = nil)
    @request = request
  end
end

# {http://www.UKMail.com/Services/Contracts/ServiceContracts}AddSendToThirdPartyResponse
#   addSendToThirdPartyResult - UKMail::SoapService::Consignment::UKMAddSendToThirdPartyWebResponse
class AddSendToThirdPartyResponse
  attr_accessor :addSendToThirdPartyResult

  def initialize(addSendToThirdPartyResult = nil)
    @addSendToThirdPartyResult = addSendToThirdPartyResult
  end
end

# {http://www.UKMail.com/Services/Contracts/ServiceContracts}CancelConsignment
#   request - UKMail::SoapService::Consignment::CancelConsignmentWebRequest
class CancelConsignment
  attr_accessor :request

  def initialize(request = nil)
    @request = request
  end
end

# {http://www.UKMail.com/Services/Contracts/ServiceContracts}CancelConsignmentResponse
#   cancelConsignmentResult - UKMail::SoapService::Consignment::UKMCancelConsignmentWebResponse
class CancelConsignmentResponse
  attr_accessor :cancelConsignmentResult

  def initialize(cancelConsignmentResult = nil)
    @cancelConsignmentResult = cancelConsignmentResult
  end
end

# {http://www.UKMail.com/Services/Contracts/ServiceContracts}CancelReturn
#   request - UKMail::SoapService::Consignment::CancelReturnWebRequest
class CancelReturn
  attr_accessor :request

  def initialize(request = nil)
    @request = request
  end
end

# {http://www.UKMail.com/Services/Contracts/ServiceContracts}CancelReturnResponse
#   cancelReturnResult - UKMail::SoapService::Consignment::UKMCancelReturnWebResponse
class CancelReturnResponse
  attr_accessor :cancelReturnResult

  def initialize(cancelReturnResult = nil)
    @cancelReturnResult = cancelReturnResult
  end
end

# {http://www.UKMail.com/Services/Contracts/ServiceContracts}AddDomesticConsignmentDeferred
#   request - UKMail::SoapService::Consignment::AddDomesticConsignmentDeferredWebRequest
class AddDomesticConsignmentDeferred
  attr_accessor :request

  def initialize(request = nil)
    @request = request
  end
end

# {http://www.UKMail.com/Services/Contracts/ServiceContracts}AddDomesticConsignmentDeferredResponse
#   addDomesticConsignmentDeferredResult - UKMail::SoapService::Consignment::UKMAddDomesticConsignmentWebResponse
class AddDomesticConsignmentDeferredResponse
  attr_accessor :addDomesticConsignmentDeferredResult

  def initialize(addDomesticConsignmentDeferredResult = nil)
    @addDomesticConsignmentDeferredResult = addDomesticConsignmentDeferredResult
  end
end


end; end; end
