# encoding: UTF-8
# Generated by wsdl2ruby (SOAP4R-NG/2.0.6)
require_relative 'UKMConsignmentService.rb'
require_relative 'UKMConsignmentServiceMappingRegistry.rb'
require 'soap/rpc/driver'

module UKMail::SoapService::Consignment

class IUKMConsignmentService < ::SOAP::RPC::Driver
  TEST_URL = 'https://qa-api.ukmail.com/Services/UKMConsignmentServices/UKMConsignmentService.svc'
  LIVE_URL = 'https://api.ukmail.com/Services/UKMConsignmentServices/UKMConsignmentService.svc'

  Methods = [
    [ "http://www.UKMail.com/Services/IUKMConsignmentService/AddDomesticConsignmentV2",
      "addDomesticConsignmentV2",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "http://www.UKMail.com/Services/Contracts/ServiceContracts", "AddDomesticConsignmentV2"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "http://www.UKMail.com/Services/Contracts/ServiceContracts", "AddDomesticConsignmentV2Response"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "http://www.UKMail.com/Services/IUKMConsignmentService/CreateConsignmentV2",
      "createConsignmentV2",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "http://www.UKMail.com/Services/Contracts/ServiceContracts", "CreateConsignmentV2"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "http://www.UKMail.com/Services/Contracts/ServiceContracts", "CreateConsignmentV2Response"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "http://www.UKMail.com/Services/IUKMConsignmentService/CreateConsignmentV3",
      "createConsignmentV3",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "http://www.UKMail.com/Services/Contracts/ServiceContracts", "CreateConsignmentV3"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "http://www.UKMail.com/Services/Contracts/ServiceContracts", "CreateConsignmentV3Response"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "http://www.UKMail.com/Services/IUKMConsignmentService/GetLabelV2",
      "getLabelV2",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "http://www.UKMail.com/Services/Contracts/ServiceContracts", "GetLabelV2"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "http://www.UKMail.com/Services/Contracts/ServiceContracts", "GetLabelV2Response"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "http://www.UKMail.com/Services/IUKMConsignmentService/AddDomesticConsignment",
      "addDomesticConsignment",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "http://www.UKMail.com/Services/Contracts/ServiceContracts", "AddDomesticConsignment"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "http://www.UKMail.com/Services/Contracts/ServiceContracts", "AddDomesticConsignmentResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "http://www.UKMail.com/Services/IUKMConsignmentService/AddInternationalConsignment",
      "addInternationalConsignment",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "http://www.UKMail.com/Services/Contracts/ServiceContracts", "AddInternationalConsignment"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "http://www.UKMail.com/Services/Contracts/ServiceContracts", "AddInternationalConsignmentResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "http://www.UKMail.com/Services/IUKMConsignmentService/AddInternationalConsignmentV2",
      "addInternationalConsignmentV2",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "http://www.UKMail.com/Services/Contracts/ServiceContracts", "AddInternationalConsignmentV2"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "http://www.UKMail.com/Services/Contracts/ServiceContracts", "AddInternationalConsignmentV2Response"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "http://www.UKMail.com/Services/IUKMConsignmentService/AddReturnToSender",
      "addReturnToSender",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "http://www.UKMail.com/Services/Contracts/ServiceContracts", "AddReturnToSender"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "http://www.UKMail.com/Services/Contracts/ServiceContracts", "AddReturnToSenderResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "http://www.UKMail.com/Services/IUKMConsignmentService/AddSendToThirdParty",
      "addSendToThirdParty",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "http://www.UKMail.com/Services/Contracts/ServiceContracts", "AddSendToThirdParty"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "http://www.UKMail.com/Services/Contracts/ServiceContracts", "AddSendToThirdPartyResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "http://www.UKMail.com/Services/IUKMConsignmentService/CancelConsignment",
      "cancelConsignment",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "http://www.UKMail.com/Services/Contracts/ServiceContracts", "CancelConsignment"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "http://www.UKMail.com/Services/Contracts/ServiceContracts", "CancelConsignmentResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "http://www.UKMail.com/Services/IUKMConsignmentService/CancelReturn",
      "cancelReturn",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "http://www.UKMail.com/Services/Contracts/ServiceContracts", "CancelReturn"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "http://www.UKMail.com/Services/Contracts/ServiceContracts", "CancelReturnResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "http://www.UKMail.com/Services/IUKMConsignmentService/AddDomesticConsignmentDeferred",
      "addDomesticConsignmentDeferred",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "http://www.UKMail.com/Services/Contracts/ServiceContracts", "AddDomesticConsignmentDeferred"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "http://www.UKMail.com/Services/Contracts/ServiceContracts", "AddDomesticConsignmentDeferredResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "http://www.UKMail.com/Services/IUKMConsignmentService/AddDomesticConsignmentDeferredV2",
      "addDomesticConsignmentDeferredV2",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "http://www.UKMail.com/Services/Contracts/ServiceContracts", "AddDomesticConsignmentDeferredV2"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "http://www.UKMail.com/Services/Contracts/ServiceContracts", "AddDomesticConsignmentDeferredV2Response"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "http://www.UKMail.com/Services/IUKMConsignmentService/AddInternationalConsignmentV3",
      "addInternationalConsignmentV3",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "http://www.UKMail.com/Services/Contracts/ServiceContracts", "AddInternationalConsignmentV3"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "http://www.UKMail.com/Services/Contracts/ServiceContracts", "AddInternationalConsignmentV3Response"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "http://www.UKMail.com/Services/IUKMConsignmentService/GetShipmentProduct",
      "getShipmentProduct",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "http://www.UKMail.com/Services/Contracts/ServiceContracts", "GetShipmentProduct"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "http://www.UKMail.com/Services/Contracts/ServiceContracts", "GetShipmentProductResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ]
  ]

  def initialize
    endpoint_url = (UKMail.config.env == :production ? LIVE_URL : TEST_URL)
    super(endpoint_url, nil)
    self.mapping_registry = UKMConsignmentServiceMappingRegistry::EncodedRegistry
    self.literal_mapping_registry = UKMConsignmentServiceMappingRegistry::LiteralRegistry
    init_methods
  end

private

  def init_methods
    Methods.each do |definitions|
      opt = definitions.last
      if opt[:request_style] == :document
        add_document_operation(*definitions)
      else
        add_rpc_operation(*definitions)
        qname = definitions[0]
        name = definitions[2]
        if qname.name != name and qname.name.capitalize == name.capitalize
          ::SOAP::Mapping.define_singleton_method(self, qname.name) do |*arg|
            __send__(name, *arg)
          end
        end
      end
    end
  end
end


end
