# encoding: UTF-8
# Generated by wsdl2ruby (SOAP4R-NG/2.0.4)
require 'xsd/qname'

module UKMail; module SoapService; module Consignment


# {http://www.UKMail.com/Services/Contracts/DataContracts}WebRequest
#   authenticationToken - SOAP::SOAPString
#   username - SOAP::SOAPString
class WebRequest
  attr_accessor :authenticationToken
  attr_accessor :username

  def initialize(authenticationToken = nil, username = nil)
    @authenticationToken = authenticationToken
    @username = username
  end
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}AddParcelShopConsignmentWebRequest
#   authenticationToken - SOAP::SOAPString
#   username - SOAP::SOAPString
#   accountNumber - SOAP::SOAPString
#   address - UKMail::SoapService::Consignment::AddressWebModel
#   alternativeRef - SOAP::SOAPString
#   businessName - SOAP::SOAPString
#   collectionJobNumber - SOAP::SOAPString
#   confirmationOfDelivery - SOAP::SOAPBoolean
#   contactName - SOAP::SOAPString
#   customersRef - SOAP::SOAPString
#   email - SOAP::SOAPString
#   height - SOAP::SOAPInt
#   items - SOAP::SOAPInt
#   length - SOAP::SOAPInt
#   providerCode - SOAP::SOAPString
#   serviceKey - SOAP::SOAPInt
#   servicePointCode - SOAP::SOAPString
#   specialInstructions1 - SOAP::SOAPString
#   specialInstructions2 - SOAP::SOAPString
#   telephone - SOAP::SOAPString
#   weight - SOAP::SOAPDecimal
#   width - SOAP::SOAPInt
class AddParcelShopConsignmentWebRequest < WebRequest
  attr_accessor :authenticationToken
  attr_accessor :username
  attr_accessor :accountNumber
  attr_accessor :address
  attr_accessor :alternativeRef
  attr_accessor :businessName
  attr_accessor :collectionJobNumber
  attr_accessor :confirmationOfDelivery
  attr_accessor :contactName
  attr_accessor :customersRef
  attr_accessor :email
  attr_accessor :height
  attr_accessor :items
  attr_accessor :length
  attr_accessor :providerCode
  attr_accessor :serviceKey
  attr_accessor :servicePointCode
  attr_accessor :specialInstructions1
  attr_accessor :specialInstructions2
  attr_accessor :telephone
  attr_accessor :weight
  attr_accessor :width

  def initialize(authenticationToken = nil, username = nil, accountNumber = nil, address = nil, alternativeRef = nil, businessName = nil, collectionJobNumber = nil, confirmationOfDelivery = nil, contactName = nil, customersRef = nil, email = nil, height = nil, items = nil, length = nil, providerCode = nil, serviceKey = nil, servicePointCode = nil, specialInstructions1 = nil, specialInstructions2 = nil, telephone = nil, weight = nil, width = nil)
    @authenticationToken = authenticationToken
    @username = username
    @accountNumber = accountNumber
    @address = address
    @alternativeRef = alternativeRef
    @businessName = businessName
    @collectionJobNumber = collectionJobNumber
    @confirmationOfDelivery = confirmationOfDelivery
    @contactName = contactName
    @customersRef = customersRef
    @email = email
    @height = height
    @items = items
    @length = length
    @providerCode = providerCode
    @serviceKey = serviceKey
    @servicePointCode = servicePointCode
    @specialInstructions1 = specialInstructions1
    @specialInstructions2 = specialInstructions2
    @telephone = telephone
    @weight = weight
    @width = width
  end
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}AddParcelShopDomesticConsignmentWebRequest
#   authenticationToken - SOAP::SOAPString
#   username - SOAP::SOAPString
#   accountNumber - SOAP::SOAPString
#   address - UKMail::SoapService::Consignment::AddressWebModel
#   alternativeRef - SOAP::SOAPString
#   businessName - SOAP::SOAPString
#   collectionJobNumber - SOAP::SOAPString
#   confirmationOfDelivery - SOAP::SOAPBoolean
#   contactName - SOAP::SOAPString
#   customersRef - SOAP::SOAPString
#   email - SOAP::SOAPString
#   height - SOAP::SOAPInt
#   items - SOAP::SOAPInt
#   length - SOAP::SOAPInt
#   providerCode - SOAP::SOAPString
#   serviceKey - SOAP::SOAPInt
#   servicePointCode - SOAP::SOAPString
#   specialInstructions1 - SOAP::SOAPString
#   specialInstructions2 - SOAP::SOAPString
#   telephone - SOAP::SOAPString
#   weight - SOAP::SOAPDecimal
#   width - SOAP::SOAPInt
#   bookIn - SOAP::SOAPBoolean
#   cODAmount - SOAP::SOAPDecimal
#   confirmationEmail - SOAP::SOAPString
#   confirmationTelephone - SOAP::SOAPString
#   exchangeOnDelivery - SOAP::SOAPBoolean
#   extendedCover - SOAP::SOAPInt
#   longLength - SOAP::SOAPBoolean
#   preDeliveryNotification - UKMail::SoapService::Consignment::PreDeliveryNotificationType
#   secureLocation1 - SOAP::SOAPString
#   secureLocation2 - SOAP::SOAPString
#   signatureOptional - SOAP::SOAPBoolean
class AddParcelShopDomesticConsignmentWebRequest < AddParcelShopConsignmentWebRequest
  attr_accessor :authenticationToken
  attr_accessor :username
  attr_accessor :accountNumber
  attr_accessor :address
  attr_accessor :alternativeRef
  attr_accessor :businessName
  attr_accessor :collectionJobNumber
  attr_accessor :confirmationOfDelivery
  attr_accessor :contactName
  attr_accessor :customersRef
  attr_accessor :email
  attr_accessor :height
  attr_accessor :items
  attr_accessor :length
  attr_accessor :providerCode
  attr_accessor :serviceKey
  attr_accessor :servicePointCode
  attr_accessor :specialInstructions1
  attr_accessor :specialInstructions2
  attr_accessor :telephone
  attr_accessor :weight
  attr_accessor :width
  attr_accessor :bookIn
  attr_accessor :cODAmount
  attr_accessor :confirmationEmail
  attr_accessor :confirmationTelephone
  attr_accessor :exchangeOnDelivery
  attr_accessor :extendedCover
  attr_accessor :longLength
  attr_accessor :preDeliveryNotification
  attr_accessor :secureLocation1
  attr_accessor :secureLocation2
  attr_accessor :signatureOptional

  def initialize(authenticationToken = nil, username = nil, accountNumber = nil, address = nil, alternativeRef = nil, businessName = nil, collectionJobNumber = nil, confirmationOfDelivery = nil, contactName = nil, customersRef = nil, email = nil, height = nil, items = nil, length = nil, providerCode = nil, serviceKey = nil, servicePointCode = nil, specialInstructions1 = nil, specialInstructions2 = nil, telephone = nil, weight = nil, width = nil, bookIn = nil, cODAmount = nil, confirmationEmail = nil, confirmationTelephone = nil, exchangeOnDelivery = nil, extendedCover = nil, longLength = nil, preDeliveryNotification = nil, secureLocation1 = nil, secureLocation2 = nil, signatureOptional = nil)
    @authenticationToken = authenticationToken
    @username = username
    @accountNumber = accountNumber
    @address = address
    @alternativeRef = alternativeRef
    @businessName = businessName
    @collectionJobNumber = collectionJobNumber
    @confirmationOfDelivery = confirmationOfDelivery
    @contactName = contactName
    @customersRef = customersRef
    @email = email
    @height = height
    @items = items
    @length = length
    @providerCode = providerCode
    @serviceKey = serviceKey
    @servicePointCode = servicePointCode
    @specialInstructions1 = specialInstructions1
    @specialInstructions2 = specialInstructions2
    @telephone = telephone
    @weight = weight
    @width = width
    @bookIn = bookIn
    @cODAmount = cODAmount
    @confirmationEmail = confirmationEmail
    @confirmationTelephone = confirmationTelephone
    @exchangeOnDelivery = exchangeOnDelivery
    @extendedCover = extendedCover
    @longLength = longLength
    @preDeliveryNotification = preDeliveryNotification
    @secureLocation1 = secureLocation1
    @secureLocation2 = secureLocation2
    @signatureOptional = signatureOptional
  end
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}AddParcelShopDomesticConsignmentWebRequestV2
#   authenticationToken - SOAP::SOAPString
#   username - SOAP::SOAPString
#   accountNumber - SOAP::SOAPString
#   address - UKMail::SoapService::Consignment::AddressWebModel
#   alternativeRef - SOAP::SOAPString
#   businessName - SOAP::SOAPString
#   collectionJobNumber - SOAP::SOAPString
#   confirmationOfDelivery - SOAP::SOAPBoolean
#   contactName - SOAP::SOAPString
#   customersRef - SOAP::SOAPString
#   email - SOAP::SOAPString
#   height - SOAP::SOAPInt
#   items - SOAP::SOAPInt
#   length - SOAP::SOAPInt
#   providerCode - SOAP::SOAPString
#   serviceKey - SOAP::SOAPInt
#   servicePointCode - SOAP::SOAPString
#   specialInstructions1 - SOAP::SOAPString
#   specialInstructions2 - SOAP::SOAPString
#   telephone - SOAP::SOAPString
#   weight - SOAP::SOAPDecimal
#   width - SOAP::SOAPInt
#   bookIn - SOAP::SOAPBoolean
#   cODAmount - SOAP::SOAPDecimal
#   confirmationEmail - SOAP::SOAPString
#   confirmationTelephone - SOAP::SOAPString
#   exchangeOnDelivery - SOAP::SOAPBoolean
#   extendedCover - SOAP::SOAPInt
#   longLength - SOAP::SOAPBoolean
#   preDeliveryNotification - UKMail::SoapService::Consignment::PreDeliveryNotificationType
#   secureLocation1 - SOAP::SOAPString
#   secureLocation2 - SOAP::SOAPString
#   signatureOptional - SOAP::SOAPBoolean
#   basicCustomsDeclaration - UKMail::SoapService::Consignment::BasicCustomsDeclaration
#   fullCustomsDeclaration - UKMail::SoapService::Consignment::CustomsDeclaration
class AddParcelShopDomesticConsignmentWebRequestV2 < AddParcelShopDomesticConsignmentWebRequest
  attr_accessor :authenticationToken
  attr_accessor :username
  attr_accessor :accountNumber
  attr_accessor :address
  attr_accessor :alternativeRef
  attr_accessor :businessName
  attr_accessor :collectionJobNumber
  attr_accessor :confirmationOfDelivery
  attr_accessor :contactName
  attr_accessor :customersRef
  attr_accessor :email
  attr_accessor :height
  attr_accessor :items
  attr_accessor :length
  attr_accessor :providerCode
  attr_accessor :serviceKey
  attr_accessor :servicePointCode
  attr_accessor :specialInstructions1
  attr_accessor :specialInstructions2
  attr_accessor :telephone
  attr_accessor :weight
  attr_accessor :width
  attr_accessor :bookIn
  attr_accessor :cODAmount
  attr_accessor :confirmationEmail
  attr_accessor :confirmationTelephone
  attr_accessor :exchangeOnDelivery
  attr_accessor :extendedCover
  attr_accessor :longLength
  attr_accessor :preDeliveryNotification
  attr_accessor :secureLocation1
  attr_accessor :secureLocation2
  attr_accessor :signatureOptional
  attr_accessor :basicCustomsDeclaration
  attr_accessor :fullCustomsDeclaration

  def initialize(authenticationToken = nil, username = nil, accountNumber = nil, address = nil, alternativeRef = nil, businessName = nil, collectionJobNumber = nil, confirmationOfDelivery = nil, contactName = nil, customersRef = nil, email = nil, height = nil, items = nil, length = nil, providerCode = nil, serviceKey = nil, servicePointCode = nil, specialInstructions1 = nil, specialInstructions2 = nil, telephone = nil, weight = nil, width = nil, bookIn = nil, cODAmount = nil, confirmationEmail = nil, confirmationTelephone = nil, exchangeOnDelivery = nil, extendedCover = nil, longLength = nil, preDeliveryNotification = nil, secureLocation1 = nil, secureLocation2 = nil, signatureOptional = nil, basicCustomsDeclaration = nil, fullCustomsDeclaration = nil)
    @authenticationToken = authenticationToken
    @username = username
    @accountNumber = accountNumber
    @address = address
    @alternativeRef = alternativeRef
    @businessName = businessName
    @collectionJobNumber = collectionJobNumber
    @confirmationOfDelivery = confirmationOfDelivery
    @contactName = contactName
    @customersRef = customersRef
    @email = email
    @height = height
    @items = items
    @length = length
    @providerCode = providerCode
    @serviceKey = serviceKey
    @servicePointCode = servicePointCode
    @specialInstructions1 = specialInstructions1
    @specialInstructions2 = specialInstructions2
    @telephone = telephone
    @weight = weight
    @width = width
    @bookIn = bookIn
    @cODAmount = cODAmount
    @confirmationEmail = confirmationEmail
    @confirmationTelephone = confirmationTelephone
    @exchangeOnDelivery = exchangeOnDelivery
    @extendedCover = extendedCover
    @longLength = longLength
    @preDeliveryNotification = preDeliveryNotification
    @secureLocation1 = secureLocation1
    @secureLocation2 = secureLocation2
    @signatureOptional = signatureOptional
    @basicCustomsDeclaration = basicCustomsDeclaration
    @fullCustomsDeclaration = fullCustomsDeclaration
  end
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}AddParcelShopInternationalConsignmentWebRequest
#   authenticationToken - SOAP::SOAPString
#   username - SOAP::SOAPString
#   accountNumber - SOAP::SOAPString
#   address - UKMail::SoapService::Consignment::AddressWebModel
#   alternativeRef - SOAP::SOAPString
#   businessName - SOAP::SOAPString
#   collectionJobNumber - SOAP::SOAPString
#   confirmationOfDelivery - SOAP::SOAPBoolean
#   contactName - SOAP::SOAPString
#   customersRef - SOAP::SOAPString
#   email - SOAP::SOAPString
#   height - SOAP::SOAPInt
#   items - SOAP::SOAPInt
#   length - SOAP::SOAPInt
#   providerCode - SOAP::SOAPString
#   serviceKey - SOAP::SOAPInt
#   servicePointCode - SOAP::SOAPString
#   specialInstructions1 - SOAP::SOAPString
#   specialInstructions2 - SOAP::SOAPString
#   telephone - SOAP::SOAPString
#   weight - SOAP::SOAPDecimal
#   width - SOAP::SOAPInt
#   currencyCode - SOAP::SOAPString
#   documentsOnly - SOAP::SOAPBoolean
#   extendedCoverRequired - SOAP::SOAPBoolean
#   goodsDescription1 - SOAP::SOAPString
#   goodsDescription2 - SOAP::SOAPString
#   goodsDescription3 - SOAP::SOAPString
#   inFreeCirculationEU - SOAP::SOAPBoolean
#   invoiceType - UKMail::SoapService::Consignment::ParcelShopInvoiceTypeList
#   noDangerousGoods - SOAP::SOAPBoolean
#   value - SOAP::SOAPDecimal
class AddParcelShopInternationalConsignmentWebRequest < AddParcelShopConsignmentWebRequest
  attr_accessor :authenticationToken
  attr_accessor :username
  attr_accessor :accountNumber
  attr_accessor :address
  attr_accessor :alternativeRef
  attr_accessor :businessName
  attr_accessor :collectionJobNumber
  attr_accessor :confirmationOfDelivery
  attr_accessor :contactName
  attr_accessor :customersRef
  attr_accessor :email
  attr_accessor :height
  attr_accessor :items
  attr_accessor :length
  attr_accessor :providerCode
  attr_accessor :serviceKey
  attr_accessor :servicePointCode
  attr_accessor :specialInstructions1
  attr_accessor :specialInstructions2
  attr_accessor :telephone
  attr_accessor :weight
  attr_accessor :width
  attr_accessor :currencyCode
  attr_accessor :documentsOnly
  attr_accessor :extendedCoverRequired
  attr_accessor :goodsDescription1
  attr_accessor :goodsDescription2
  attr_accessor :goodsDescription3
  attr_accessor :inFreeCirculationEU
  attr_accessor :invoiceType
  attr_accessor :noDangerousGoods
  attr_accessor :value

  def initialize(authenticationToken = nil, username = nil, accountNumber = nil, address = nil, alternativeRef = nil, businessName = nil, collectionJobNumber = nil, confirmationOfDelivery = nil, contactName = nil, customersRef = nil, email = nil, height = nil, items = nil, length = nil, providerCode = nil, serviceKey = nil, servicePointCode = nil, specialInstructions1 = nil, specialInstructions2 = nil, telephone = nil, weight = nil, width = nil, currencyCode = nil, documentsOnly = nil, extendedCoverRequired = nil, goodsDescription1 = nil, goodsDescription2 = nil, goodsDescription3 = nil, inFreeCirculationEU = nil, invoiceType = nil, noDangerousGoods = nil, value = nil)
    @authenticationToken = authenticationToken
    @username = username
    @accountNumber = accountNumber
    @address = address
    @alternativeRef = alternativeRef
    @businessName = businessName
    @collectionJobNumber = collectionJobNumber
    @confirmationOfDelivery = confirmationOfDelivery
    @contactName = contactName
    @customersRef = customersRef
    @email = email
    @height = height
    @items = items
    @length = length
    @providerCode = providerCode
    @serviceKey = serviceKey
    @servicePointCode = servicePointCode
    @specialInstructions1 = specialInstructions1
    @specialInstructions2 = specialInstructions2
    @telephone = telephone
    @weight = weight
    @width = width
    @currencyCode = currencyCode
    @documentsOnly = documentsOnly
    @extendedCoverRequired = extendedCoverRequired
    @goodsDescription1 = goodsDescription1
    @goodsDescription2 = goodsDescription2
    @goodsDescription3 = goodsDescription3
    @inFreeCirculationEU = inFreeCirculationEU
    @invoiceType = invoiceType
    @noDangerousGoods = noDangerousGoods
    @value = value
  end
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}AddParcelShopConsignmentDeferredWebRequest
#   authenticationToken - SOAP::SOAPString
#   username - SOAP::SOAPString
#   accountNumber - SOAP::SOAPString
#   address - UKMail::SoapService::Consignment::AddressWebModel
#   alternativeRef - SOAP::SOAPString
#   businessName - SOAP::SOAPString
#   collectionDate - SOAP::SOAPDateTime
#   confirmationOfDelivery - SOAP::SOAPBoolean
#   contactName - SOAP::SOAPString
#   customersRef - SOAP::SOAPString
#   email - SOAP::SOAPString
#   height - SOAP::SOAPInt
#   items - SOAP::SOAPInt
#   labelFormat - UKMail::SoapService::Consignment::LabelFormatType
#   length - SOAP::SOAPInt
#   providerCode - SOAP::SOAPString
#   serviceKey - SOAP::SOAPInt
#   servicePointCode - SOAP::SOAPString
#   specialInstructions1 - SOAP::SOAPString
#   specialInstructions2 - SOAP::SOAPString
#   telephone - SOAP::SOAPString
#   weight - SOAP::SOAPDecimal
#   width - SOAP::SOAPInt
class AddParcelShopConsignmentDeferredWebRequest < WebRequest
  attr_accessor :authenticationToken
  attr_accessor :username
  attr_accessor :accountNumber
  attr_accessor :address
  attr_accessor :alternativeRef
  attr_accessor :businessName
  attr_accessor :collectionDate
  attr_accessor :confirmationOfDelivery
  attr_accessor :contactName
  attr_accessor :customersRef
  attr_accessor :email
  attr_accessor :height
  attr_accessor :items
  attr_accessor :labelFormat
  attr_accessor :length
  attr_accessor :providerCode
  attr_accessor :serviceKey
  attr_accessor :servicePointCode
  attr_accessor :specialInstructions1
  attr_accessor :specialInstructions2
  attr_accessor :telephone
  attr_accessor :weight
  attr_accessor :width

  def initialize(authenticationToken = nil, username = nil, accountNumber = nil, address = nil, alternativeRef = nil, businessName = nil, collectionDate = nil, confirmationOfDelivery = nil, contactName = nil, customersRef = nil, email = nil, height = nil, items = nil, labelFormat = nil, length = nil, providerCode = nil, serviceKey = nil, servicePointCode = nil, specialInstructions1 = nil, specialInstructions2 = nil, telephone = nil, weight = nil, width = nil)
    @authenticationToken = authenticationToken
    @username = username
    @accountNumber = accountNumber
    @address = address
    @alternativeRef = alternativeRef
    @businessName = businessName
    @collectionDate = collectionDate
    @confirmationOfDelivery = confirmationOfDelivery
    @contactName = contactName
    @customersRef = customersRef
    @email = email
    @height = height
    @items = items
    @labelFormat = labelFormat
    @length = length
    @providerCode = providerCode
    @serviceKey = serviceKey
    @servicePointCode = servicePointCode
    @specialInstructions1 = specialInstructions1
    @specialInstructions2 = specialInstructions2
    @telephone = telephone
    @weight = weight
    @width = width
  end
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}AddParcelShopDomesticConsignmentDeferredWebRequest
#   authenticationToken - SOAP::SOAPString
#   username - SOAP::SOAPString
#   accountNumber - SOAP::SOAPString
#   address - UKMail::SoapService::Consignment::AddressWebModel
#   alternativeRef - SOAP::SOAPString
#   businessName - SOAP::SOAPString
#   collectionDate - SOAP::SOAPDateTime
#   confirmationOfDelivery - SOAP::SOAPBoolean
#   contactName - SOAP::SOAPString
#   customersRef - SOAP::SOAPString
#   email - SOAP::SOAPString
#   height - SOAP::SOAPInt
#   items - SOAP::SOAPInt
#   labelFormat - UKMail::SoapService::Consignment::LabelFormatType
#   length - SOAP::SOAPInt
#   providerCode - SOAP::SOAPString
#   serviceKey - SOAP::SOAPInt
#   servicePointCode - SOAP::SOAPString
#   specialInstructions1 - SOAP::SOAPString
#   specialInstructions2 - SOAP::SOAPString
#   telephone - SOAP::SOAPString
#   weight - SOAP::SOAPDecimal
#   width - SOAP::SOAPInt
#   bookIn - SOAP::SOAPBoolean
#   cODAmount - SOAP::SOAPDecimal
#   confirmationEmail - SOAP::SOAPString
#   confirmationTelephone - SOAP::SOAPString
#   exchangeOnDelivery - SOAP::SOAPBoolean
#   extendedCover - SOAP::SOAPInt
#   longLength - SOAP::SOAPBoolean
#   preDeliveryNotification - UKMail::SoapService::Consignment::PreDeliveryNotificationType
#   secureLocation1 - SOAP::SOAPString
#   secureLocation2 - SOAP::SOAPString
#   signatureOptional - SOAP::SOAPBoolean
class AddParcelShopDomesticConsignmentDeferredWebRequest < AddParcelShopConsignmentDeferredWebRequest
  attr_accessor :authenticationToken
  attr_accessor :username
  attr_accessor :accountNumber
  attr_accessor :address
  attr_accessor :alternativeRef
  attr_accessor :businessName
  attr_accessor :collectionDate
  attr_accessor :confirmationOfDelivery
  attr_accessor :contactName
  attr_accessor :customersRef
  attr_accessor :email
  attr_accessor :height
  attr_accessor :items
  attr_accessor :labelFormat
  attr_accessor :length
  attr_accessor :providerCode
  attr_accessor :serviceKey
  attr_accessor :servicePointCode
  attr_accessor :specialInstructions1
  attr_accessor :specialInstructions2
  attr_accessor :telephone
  attr_accessor :weight
  attr_accessor :width
  attr_accessor :bookIn
  attr_accessor :cODAmount
  attr_accessor :confirmationEmail
  attr_accessor :confirmationTelephone
  attr_accessor :exchangeOnDelivery
  attr_accessor :extendedCover
  attr_accessor :longLength
  attr_accessor :preDeliveryNotification
  attr_accessor :secureLocation1
  attr_accessor :secureLocation2
  attr_accessor :signatureOptional

  def initialize(authenticationToken = nil, username = nil, accountNumber = nil, address = nil, alternativeRef = nil, businessName = nil, collectionDate = nil, confirmationOfDelivery = nil, contactName = nil, customersRef = nil, email = nil, height = nil, items = nil, labelFormat = nil, length = nil, providerCode = nil, serviceKey = nil, servicePointCode = nil, specialInstructions1 = nil, specialInstructions2 = nil, telephone = nil, weight = nil, width = nil, bookIn = nil, cODAmount = nil, confirmationEmail = nil, confirmationTelephone = nil, exchangeOnDelivery = nil, extendedCover = nil, longLength = nil, preDeliveryNotification = nil, secureLocation1 = nil, secureLocation2 = nil, signatureOptional = nil)
    @authenticationToken = authenticationToken
    @username = username
    @accountNumber = accountNumber
    @address = address
    @alternativeRef = alternativeRef
    @businessName = businessName
    @collectionDate = collectionDate
    @confirmationOfDelivery = confirmationOfDelivery
    @contactName = contactName
    @customersRef = customersRef
    @email = email
    @height = height
    @items = items
    @labelFormat = labelFormat
    @length = length
    @providerCode = providerCode
    @serviceKey = serviceKey
    @servicePointCode = servicePointCode
    @specialInstructions1 = specialInstructions1
    @specialInstructions2 = specialInstructions2
    @telephone = telephone
    @weight = weight
    @width = width
    @bookIn = bookIn
    @cODAmount = cODAmount
    @confirmationEmail = confirmationEmail
    @confirmationTelephone = confirmationTelephone
    @exchangeOnDelivery = exchangeOnDelivery
    @extendedCover = extendedCover
    @longLength = longLength
    @preDeliveryNotification = preDeliveryNotification
    @secureLocation1 = secureLocation1
    @secureLocation2 = secureLocation2
    @signatureOptional = signatureOptional
  end
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}AddParcelShopPacketConsignmentWebRequest
#   authenticationToken - SOAP::SOAPString
#   username - SOAP::SOAPString
#   accountNumber - SOAP::SOAPString
#   collectionJobNumber - SOAP::SOAPString
#   contactName - SOAP::SOAPString
#   businessName - SOAP::SOAPString
#   address - UKMail::SoapService::Consignment::PacketAddressWebModel
#   customersRef - SOAP::SOAPString
#   alternativeRef - SOAP::SOAPString
#   weightInGrams - SOAP::SOAPInt
#   packetLength - SOAP::SOAPInt
#   packetWidth - SOAP::SOAPInt
#   packetHeight - SOAP::SOAPInt
#   deliveryMessage1 - SOAP::SOAPString
#   deliveryMessage2 - SOAP::SOAPString
#   providerCode - SOAP::SOAPString
#   servicePointCode - SOAP::SOAPString
class AddParcelShopPacketConsignmentWebRequest < WebRequest
  attr_accessor :authenticationToken
  attr_accessor :username
  attr_accessor :accountNumber
  attr_accessor :collectionJobNumber
  attr_accessor :contactName
  attr_accessor :businessName
  attr_accessor :address
  attr_accessor :customersRef
  attr_accessor :alternativeRef
  attr_accessor :weightInGrams
  attr_accessor :packetLength
  attr_accessor :packetWidth
  attr_accessor :packetHeight
  attr_accessor :deliveryMessage1
  attr_accessor :deliveryMessage2
  attr_accessor :providerCode
  attr_accessor :servicePointCode

  def initialize(authenticationToken = nil, username = nil, accountNumber = nil, collectionJobNumber = nil, contactName = nil, businessName = nil, address = nil, customersRef = nil, alternativeRef = nil, weightInGrams = nil, packetLength = nil, packetWidth = nil, packetHeight = nil, deliveryMessage1 = nil, deliveryMessage2 = nil, providerCode = nil, servicePointCode = nil)
    @authenticationToken = authenticationToken
    @username = username
    @accountNumber = accountNumber
    @collectionJobNumber = collectionJobNumber
    @contactName = contactName
    @businessName = businessName
    @address = address
    @customersRef = customersRef
    @alternativeRef = alternativeRef
    @weightInGrams = weightInGrams
    @packetLength = packetLength
    @packetWidth = packetWidth
    @packetHeight = packetHeight
    @deliveryMessage1 = deliveryMessage1
    @deliveryMessage2 = deliveryMessage2
    @providerCode = providerCode
    @servicePointCode = servicePointCode
  end
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}AddressWebModel
#   address1 - SOAP::SOAPString
#   address2 - SOAP::SOAPString
#   address3 - SOAP::SOAPString
#   countryCode - SOAP::SOAPString
#   county - SOAP::SOAPString
#   postalTown - SOAP::SOAPString
#   postcode - SOAP::SOAPString
class AddressWebModel
  attr_accessor :address1
  attr_accessor :address2
  attr_accessor :address3
  attr_accessor :countryCode
  attr_accessor :county
  attr_accessor :postalTown
  attr_accessor :postcode

  def initialize(address1 = nil, address2 = nil, address3 = nil, countryCode = nil, county = nil, postalTown = nil, postcode = nil)
    @address1 = address1
    @address2 = address2
    @address3 = address3
    @countryCode = countryCode
    @county = county
    @postalTown = postalTown
    @postcode = postcode
  end
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}UKMWebResponse
#   errors - UKMail::SoapService::Consignment::ArrayOfUKMWebError
#   result - UKMail::SoapService::Consignment::UKMResultState
#   warnings - UKMail::SoapService::Consignment::ArrayOfUKMWebWarning
class UKMWebResponse
  attr_accessor :errors
  attr_accessor :result
  attr_accessor :warnings

  def initialize(errors = nil, result = nil, warnings = nil)
    @errors = errors
    @result = result
    @warnings = warnings
  end
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}UKMAddDomesticConsignmentWebResponse
#   errors - UKMail::SoapService::Consignment::ArrayOfUKMWebError
#   result - UKMail::SoapService::Consignment::UKMResultState
#   warnings - UKMail::SoapService::Consignment::ArrayOfUKMWebWarning
#   consignmentNumber - SOAP::SOAPString
#   labels - UKMail::SoapService::Consignment::ArrayOfbase64Binary
class UKMAddDomesticConsignmentWebResponse < UKMWebResponse
  attr_accessor :errors
  attr_accessor :result
  attr_accessor :warnings
  attr_accessor :consignmentNumber
  attr_accessor :labels

  def initialize(errors = nil, result = nil, warnings = nil, consignmentNumber = nil, labels = nil)
    @errors = errors
    @result = result
    @warnings = warnings
    @consignmentNumber = consignmentNumber
    @labels = labels
  end
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}UKMAddInternationalConsignmentWebResponse
#   errors - UKMail::SoapService::Consignment::ArrayOfUKMWebError
#   result - UKMail::SoapService::Consignment::UKMResultState
#   warnings - UKMail::SoapService::Consignment::ArrayOfUKMWebWarning
#   consignmentNumber - SOAP::SOAPString
#   invoiceBytes - SOAP::SOAPBase64
#   labels - UKMail::SoapService::Consignment::ArrayOfbase64Binary
class UKMAddInternationalConsignmentWebResponse < UKMWebResponse
  attr_accessor :errors
  attr_accessor :result
  attr_accessor :warnings
  attr_accessor :consignmentNumber
  attr_accessor :invoiceBytes
  attr_accessor :labels

  def initialize(errors = nil, result = nil, warnings = nil, consignmentNumber = nil, invoiceBytes = nil, labels = nil)
    @errors = errors
    @result = result
    @warnings = warnings
    @consignmentNumber = consignmentNumber
    @invoiceBytes = invoiceBytes
    @labels = labels
  end
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}UKMAddPacketConsignmentWebResponse
#   errors - UKMail::SoapService::Consignment::ArrayOfUKMWebError
#   result - UKMail::SoapService::Consignment::UKMResultState
#   warnings - UKMail::SoapService::Consignment::ArrayOfUKMWebWarning
#   consignmentNumber - SOAP::SOAPString
#   labels - UKMail::SoapService::Consignment::ArrayOfbase64Binary
class UKMAddPacketConsignmentWebResponse < UKMWebResponse
  attr_accessor :errors
  attr_accessor :result
  attr_accessor :warnings
  attr_accessor :consignmentNumber
  attr_accessor :labels

  def initialize(errors = nil, result = nil, warnings = nil, consignmentNumber = nil, labels = nil)
    @errors = errors
    @result = result
    @warnings = warnings
    @consignmentNumber = consignmentNumber
    @labels = labels
  end
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}ArrayOfUKMWebError
class ArrayOfUKMWebError < ::Array
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}UKMWebError
#   code - SOAP::SOAPInt
#   description - SOAP::SOAPString
class UKMWebError
  attr_accessor :code
  attr_accessor :description

  def initialize(code = nil, description = nil)
    @code = code
    @description = description
  end
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}ArrayOfUKMWebWarning
class ArrayOfUKMWebWarning < ::Array
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}UKMWebWarning
#   code - SOAP::SOAPInt
#   description - SOAP::SOAPString
class UKMWebWarning
  attr_accessor :code
  attr_accessor :description

  def initialize(code = nil, description = nil)
    @code = code
    @description = description
  end
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}BasicCustomsDeclaration
#   currencyCode - SOAP::SOAPString
#   descriptionOfGoods - SOAP::SOAPString
#   documentsOnly - SOAP::SOAPBoolean
#   invoiceType - UKMail::SoapService::Consignment::InvoiceType
#   value - SOAP::SOAPDecimal
class BasicCustomsDeclaration
  attr_accessor :currencyCode
  attr_accessor :descriptionOfGoods
  attr_accessor :documentsOnly
  attr_accessor :invoiceType
  attr_accessor :value

  def initialize(currencyCode = nil, descriptionOfGoods = nil, documentsOnly = nil, invoiceType = nil, value = nil)
    @currencyCode = currencyCode
    @descriptionOfGoods = descriptionOfGoods
    @documentsOnly = documentsOnly
    @invoiceType = invoiceType
    @value = value
  end
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}PacketAddressWebModel
#   address1 - SOAP::SOAPString
#   address2 - SOAP::SOAPString
#   address3 - SOAP::SOAPString
#   county - SOAP::SOAPString
#   postalTown - SOAP::SOAPString
#   postcode - SOAP::SOAPString
class PacketAddressWebModel
  attr_accessor :address1
  attr_accessor :address2
  attr_accessor :address3
  attr_accessor :county
  attr_accessor :postalTown
  attr_accessor :postcode

  def initialize(address1 = nil, address2 = nil, address3 = nil, county = nil, postalTown = nil, postcode = nil)
    @address1 = address1
    @address2 = address2
    @address3 = address3
    @county = county
    @postalTown = postalTown
    @postcode = postcode
  end
end

# {http://schemas.microsoft.com/2003/10/Serialization/Arrays}ArrayOfbase64Binary
class ArrayOfbase64Binary < ::Array
end

# {http://schemas.datacontract.org/2004/07/UKMWebAPICommon.WebRequests}CustomsDeclaration
#   articles - UKMail::SoapService::Consignment::Articles
#   currencyCode - SOAP::SOAPString
#   invoiceDate - SOAP::SOAPDateTime
#   invoiceNumber - SOAP::SOAPString
#   invoiceType - UKMail::SoapService::Consignment::InvoiceType
#   reasonForExport - UKMail::SoapService::Consignment::ReasonForExport
#   shippingCharges - SOAP::SOAPDecimal
#   termsOfDelivery - UKMail::SoapService::Consignment::TermsOfDelivery
#   totalArticles - SOAP::SOAPInt
#   totalValue - SOAP::SOAPDecimal
class CustomsDeclaration
  attr_accessor :articles
  attr_accessor :currencyCode
  attr_accessor :invoiceDate
  attr_accessor :invoiceNumber
  attr_accessor :invoiceType
  attr_accessor :reasonForExport
  attr_accessor :shippingCharges
  attr_accessor :termsOfDelivery
  attr_accessor :totalArticles
  attr_accessor :totalValue

  def initialize(articles = nil, currencyCode = nil, invoiceDate = nil, invoiceNumber = nil, invoiceType = nil, reasonForExport = nil, shippingCharges = nil, termsOfDelivery = nil, totalArticles = nil, totalValue = nil)
    @articles = articles
    @currencyCode = currencyCode
    @invoiceDate = invoiceDate
    @invoiceNumber = invoiceNumber
    @invoiceType = invoiceType
    @reasonForExport = reasonForExport
    @shippingCharges = shippingCharges
    @termsOfDelivery = termsOfDelivery
    @totalArticles = totalArticles
    @totalValue = totalValue
  end
end

# {http://schemas.datacontract.org/2004/07/UKMWebAPICommon.WebRequests}Articles
#   article - UKMail::SoapService::Consignment::ArrayOfArticleDetail
class Articles
  attr_accessor :article

  def initialize(article = nil)
    @article = article
  end
end

# {http://schemas.datacontract.org/2004/07/UKMWebAPICommon.WebRequests}ArrayOfArticleDetail
class ArrayOfArticleDetail < ::Array
end

# {http://schemas.datacontract.org/2004/07/UKMWebAPICommon.WebRequests}ArticleDetail
#   commodityCode - SOAP::SOAPString
#   countryOfManufacture - SOAP::SOAPString
#   goodsDescription - SOAP::SOAPString
#   quantity - SOAP::SOAPInt
#   unitValue - SOAP::SOAPDouble
#   unitWeight - SOAP::SOAPDouble
class ArticleDetail
  attr_accessor :commodityCode
  attr_accessor :countryOfManufacture
  attr_accessor :goodsDescription
  attr_accessor :quantity
  attr_accessor :unitValue
  attr_accessor :unitWeight

  def initialize(commodityCode = nil, countryOfManufacture = nil, goodsDescription = nil, quantity = nil, unitValue = nil, unitWeight = nil)
    @commodityCode = commodityCode
    @countryOfManufacture = countryOfManufacture
    @goodsDescription = goodsDescription
    @quantity = quantity
    @unitValue = unitValue
    @unitWeight = unitWeight
  end
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}PreDeliveryNotificationType
class PreDeliveryNotificationType < ::String
  Email = new("Email")
  NonRequired = new("NonRequired")
  Telephone = new("Telephone")
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}InvoiceType
class InvoiceType < ::String
  Commercial = new("commercial")
  None = new("none")
  Proforma = new("proforma")
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}LabelFormatType
class LabelFormatType < ::String
  PNG6x4 = new("PNG6x4")
  ZPL200dpi6x4 = new("ZPL200dpi6x4")
end

# {http://www.UKMail.com/Services/Contracts/DataContracts}ParcelShopInvoiceTypeList
class ParcelShopInvoiceTypeList < ::String
  Commercial = new("Commercial")
  None = new("None")
  ProForma = new("ProForma")
end

# {http://schemas.datacontract.org/2004/07/UKMWebAPICommon.WebResponses}UKMResultState
class UKMResultState < ::String
  Failed = new("Failed")
  Successful = new("Successful")
  Unknown = new("Unknown")
end

# {http://schemas.datacontract.org/2004/07/UKMWebAPICommon.WebRequests}ReasonForExport
class ReasonForExport < ::String
  CommercialSale = new("commercial sale")
  CommercialSample = new("commercial sample")
  Documents = new("documents")
  Gift = new("gift")
  Repairs = new("repairs")
  ReturnedGoods = new("returned goods")
end

# {http://schemas.datacontract.org/2004/07/UKMWebAPICommon.WebRequests}TermsOfDelivery
class TermsOfDelivery < ::String
  DAP = new("DAP")
  DDP = new("DDP")
end

# {http://www.UKMail.com/Services/Contracts/ServiceContracts}AddDomesticConsignment
#   request - UKMail::SoapService::Consignment::AddParcelShopDomesticConsignmentWebRequest
class AddDomesticConsignment
  attr_accessor :request

  def initialize(request = nil)
    @request = request
  end
end

# {http://www.UKMail.com/Services/Contracts/ServiceContracts}AddDomesticConsignmentResponse
#   addDomesticConsignmentResult - UKMail::SoapService::Consignment::UKMAddDomesticConsignmentWebResponse
class AddDomesticConsignmentResponse
  attr_accessor :addDomesticConsignmentResult

  def initialize(addDomesticConsignmentResult = nil)
    @addDomesticConsignmentResult = addDomesticConsignmentResult
  end
end

# {http://www.UKMail.com/Services/Contracts/ServiceContracts}AddDomesticConsignmentV2
#   request - UKMail::SoapService::Consignment::AddParcelShopDomesticConsignmentWebRequestV2
class AddDomesticConsignmentV2
  attr_accessor :request

  def initialize(request = nil)
    @request = request
  end
end

# {http://www.UKMail.com/Services/Contracts/ServiceContracts}AddDomesticConsignmentV2Response
#   addDomesticConsignmentV2Result - UKMail::SoapService::Consignment::UKMAddDomesticConsignmentWebResponse
class AddDomesticConsignmentV2Response
  attr_accessor :addDomesticConsignmentV2Result

  def initialize(addDomesticConsignmentV2Result = nil)
    @addDomesticConsignmentV2Result = addDomesticConsignmentV2Result
  end
end

# {http://www.UKMail.com/Services/Contracts/ServiceContracts}AddDomesticConsignmentDeferred
#   request - UKMail::SoapService::Consignment::AddParcelShopDomesticConsignmentDeferredWebRequest
class AddDomesticConsignmentDeferred
  attr_accessor :request

  def initialize(request = nil)
    @request = request
  end
end

# {http://www.UKMail.com/Services/Contracts/ServiceContracts}AddDomesticConsignmentDeferredResponse
#   addDomesticConsignmentDeferredResult - UKMail::SoapService::Consignment::UKMAddDomesticConsignmentWebResponse
class AddDomesticConsignmentDeferredResponse
  attr_accessor :addDomesticConsignmentDeferredResult

  def initialize(addDomesticConsignmentDeferredResult = nil)
    @addDomesticConsignmentDeferredResult = addDomesticConsignmentDeferredResult
  end
end

# {http://www.UKMail.com/Services/Contracts/ServiceContracts}AddInternationalConsignment
#   request - UKMail::SoapService::Consignment::AddParcelShopInternationalConsignmentWebRequest
class AddInternationalConsignment
  attr_accessor :request

  def initialize(request = nil)
    @request = request
  end
end

# {http://www.UKMail.com/Services/Contracts/ServiceContracts}AddInternationalConsignmentResponse
#   addInternationalConsignmentResult - UKMail::SoapService::Consignment::UKMAddInternationalConsignmentWebResponse
class AddInternationalConsignmentResponse
  attr_accessor :addInternationalConsignmentResult

  def initialize(addInternationalConsignmentResult = nil)
    @addInternationalConsignmentResult = addInternationalConsignmentResult
  end
end

# {http://www.UKMail.com/Services/Contracts/ServiceContracts}AddPacketConsignment
#   request - UKMail::SoapService::Consignment::AddParcelShopPacketConsignmentWebRequest
class AddPacketConsignment
  attr_accessor :request

  def initialize(request = nil)
    @request = request
  end
end

# {http://www.UKMail.com/Services/Contracts/ServiceContracts}AddPacketConsignmentResponse
#   addPacketConsignmentResult - UKMail::SoapService::Consignment::UKMAddPacketConsignmentWebResponse
class AddPacketConsignmentResponse
  attr_accessor :addPacketConsignmentResult

  def initialize(addPacketConsignmentResult = nil)
    @addPacketConsignmentResult = addPacketConsignmentResult
  end
end


end; end; end
