#!/usr/bin/env ruby
# encoding: UTF-8
# Generated by wsdl2ruby (SOAP4R-NG/2.0.3)
require_relative 'UKMCollectionServiceDriver.rb'


module UKMail::SoapService::Collection

endpoint_url = ARGV.shift
obj = IUKMCollectionService.new(endpoint_url)

# run ruby with -d to see SOAP wiredumps.
obj.wiredump_dev = STDERR if $DEBUG

# SYNOPSIS
#   bookCollection(parameters)
#
# ARGS
#   parameters      BookCollection - {http://www.UKMail.com/Services/Contracts/ServiceContracts}BookCollection
#
# RETURNS
#   parameters      BookCollectionResponse - {http://www.UKMail.com/Services/Contracts/ServiceContracts}BookCollectionResponse
#
parameters = nil
puts obj.bookCollection(parameters)




end
