#!/usr/bin/env ruby
# encoding: UTF-8
# Generated by wsdl2ruby (SOAP4R-NG/2.0.3)
require_relative 'UKMAuthenticationServiceDriver.rb'


module UKMail::SoapService::Authentication

endpoint_url = ARGV.shift
obj = IUKMAuthenticationService.new(endpoint_url)

# run ruby with -d to see SOAP wiredumps.
obj.wiredump_dev = STDERR if $DEBUG

# SYNOPSIS
#   login(parameters)
#
# ARGS
#   parameters      Login - {http://www.UKMail.com/Services/Contracts/ServiceContracts}Login
#
# RETURNS
#   parameters      LoginResponse - {http://www.UKMail.com/Services/Contracts/ServiceContracts}LoginResponse
#
parameters = nil
puts obj.login(parameters)

# SYNOPSIS
#   logout(parameters)
#
# ARGS
#   parameters      Logout - {http://www.UKMail.com/Services/Contracts/ServiceContracts}Logout
#
# RETURNS
#   parameters      LogoutResponse - {http://www.UKMail.com/Services/Contracts/ServiceContracts}LogoutResponse
#
parameters = nil
puts obj.logout(parameters)




end
