#!/usr/bin/env ruby
# encoding: UTF-8
# Generated by wsdl2ruby (SOAP4R-NG/2.0.4)
require_relative 'UKMParcelShopConsignmentServiceDriver.rb'


module UKMail::SoapService::ConsignmentV2

endpoint_url = ARGV.shift
obj = IUKMParcelShopConsignmentService.new(endpoint_url)

# run ruby with -d to see SOAP wiredumps.
obj.wiredump_dev = STDERR if $DEBUG

# SYNOPSIS
#   addDomesticConsignment(parameters)
#
# ARGS
#   parameters      AddDomesticConsignment - {http://www.UKMail.com/Services/Contracts/ServiceContracts}AddDomesticConsignment
#
# RETURNS
#   parameters      AddDomesticConsignmentResponse - {http://www.UKMail.com/Services/Contracts/ServiceContracts}AddDomesticConsignmentResponse
#
parameters = nil
puts obj.addDomesticConsignment(parameters)

# SYNOPSIS
#   addDomesticConsignmentV2(parameters)
#
# ARGS
#   parameters      AddDomesticConsignmentV2 - {http://www.UKMail.com/Services/Contracts/ServiceContracts}AddDomesticConsignmentV2
#
# RETURNS
#   parameters      AddDomesticConsignmentV2Response - {http://www.UKMail.com/Services/Contracts/ServiceContracts}AddDomesticConsignmentV2Response
#
parameters = nil
puts obj.addDomesticConsignmentV2(parameters)

# SYNOPSIS
#   addDomesticConsignmentDeferred(parameters)
#
# ARGS
#   parameters      AddDomesticConsignmentDeferred - {http://www.UKMail.com/Services/Contracts/ServiceContracts}AddDomesticConsignmentDeferred
#
# RETURNS
#   parameters      AddDomesticConsignmentDeferredResponse - {http://www.UKMail.com/Services/Contracts/ServiceContracts}AddDomesticConsignmentDeferredResponse
#
parameters = nil
puts obj.addDomesticConsignmentDeferred(parameters)

# SYNOPSIS
#   addInternationalConsignment(parameters)
#
# ARGS
#   parameters      AddInternationalConsignment - {http://www.UKMail.com/Services/Contracts/ServiceContracts}AddInternationalConsignment
#
# RETURNS
#   parameters      AddInternationalConsignmentResponse - {http://www.UKMail.com/Services/Contracts/ServiceContracts}AddInternationalConsignmentResponse
#
parameters = nil
puts obj.addInternationalConsignment(parameters)

# SYNOPSIS
#   addPacketConsignment(parameters)
#
# ARGS
#   parameters      AddPacketConsignment - {http://www.UKMail.com/Services/Contracts/ServiceContracts}AddPacketConsignment
#
# RETURNS
#   parameters      AddPacketConsignmentResponse - {http://www.UKMail.com/Services/Contracts/ServiceContracts}AddPacketConsignmentResponse
#
parameters = nil
puts obj.addPacketConsignment(parameters)




end
